### ISSUE TITLE
Undefined index: #type in form_process_actions()

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-contrib/ubercart#100]
Error message when accessing /admin/store/settings/quotes/settings/ups:

```Notice: Undefined index: #type in form_process_actions() (line 3334 of /home/robert/ubercart.backdrop.cat/core/includes/form.inc).```

**Comment by docwilmot** [comment]
The same error in `uc_cart` was solved by adding `'#type' => 'markup'` to a field declaring `'#markup' => 'whatever...'`. But there are 168 instances of `'#markup' => 'whatever...'` and I can't tell what causes the error to happen in some instances and not others, so we'll have to just fix them as they pop up.

**Comment by laryn** [comment]
I'm not seeing this error any longer.
