### ISSUE TITLE
Current tasks

### ISSUE THREAD

**Issue by docwilmot** [backdrop-contrib/ubercart#103]
Completed tasks (meaning working, with no major bugs) and tasks being worked on:

- [x] Cart
- [x] Order
- [x] Product
- [x] Store
- [x] Catalog
- [x] File downloads
- [x] Payment
- [x] Product attributes
- [x] Reports
- [x] Roles
- [x] Shipping
- [x] Shipping quotes
- [x] Tax report
- [x] Taxes
- [x] Cart Links
- [x] Google Analytics for Ubercart
- [x] Product kit
- [x] Stock
- [x] Ubercart Ajax Administration
- [x] Flat rate
- [x] U.S. Postal Service
- [ ] UPS
- [x] Weight quote
- [ ] 2Checkout
- [x] Authorize.net
- [x] Credit card
- [ ] CyberSource
- [x] Payment method pack
- [x] PayPal
- [x] Test gateway
- [x] Tests

**Comment by robertgarrigos** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Authotize.net](https://trello.com/c/GCORMn09/1-authotizenet)

**Comment by robertgarrigos** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Authotize.net](https://trello.com/c/GCORMn09/1-authotizenet)

**Comment by docwilmot** [comment]
Have now pushed PRs for all the simple stuff, which dont require external modules or APIs. 
Do you think we can now transfer to Backdrop contrib? Or wait till tests are working?

**Comment by robertgarrigos** [comment]
Why not? We might have some more feedback/help with the module in backdrop contrib. Should we make a beta release?

**Comment by docwilmot** [comment]
I'd say transfer the repo and push, but since we haven't checked everything, it would seem an alpha release may be more appropriate.

**Comment by robertgarrigos** [comment]
ok

**Comment by robertgarrigos** [comment]
done

**Comment by docwilmot** [comment]
@robertgarrigos I just pushed PRs. Right now we only have remaining the USPS, UPS, 2CO and Cybersource modules which I cannot test due to no accounts there. But in all I think UC is in good enough shape to make a beta release. There are no serious issues remaining in our queue.

Perhaps you can ask the D7 devs for advice on how to port those remaining 4 submodules.

**Comment by robertgarrigos** [comment]
thanks @docwilmot done a beta release. I'll have a look on those remaining submodules.

**Comment by laryn** [comment]
All submodules can be activated without errors so I'm going to close this one for now. Any new issues should just be reported in a new ticket.
