### ISSUE TITLE
update uc_roles tables to pr #119

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-contrib/ubercart#121]
Just a reminder we need to update uc_roles tables because fo this: https://github.com/robertgarrigos/ubercart/commit/4fb03a67873e50e1dc142908c1a3726cfcd62c65

**Comment by docwilmot** [comment]
This one is difficult. When a user upgrades from Drupal to Backdrop all roles are converted from numeric IDs to string names. So by the time the UC upgrade hook runs, there is no remaining data to match the numeric `rid`s in the `uc_roles` tables to the new role names.

As I see it, we'd need to run a script on the D7 UC data **before** the D7 to Backdrop upgrade, to save the role names from the D7 `roles` table to the `uc_roles` tables in a new column, then in the actual `uc_roles_update_N()` we swap the data from this new column to the `rid` column.

Any other thoughts?

**Comment by docwilmot** [comment]
Had an idea: when UC is upgrading, before we change the UC tables from numeric to varchar we create fake roles that match the numeric `rid`s then offer a warning after upgrade.

Example a user has a product in D7 which grants the role 'member' (`rid` = 3). While upgrading we first create a fake role like "uc_upgrade_3" and make the product to grant that instead. Then set a persistent message saying that the product roles need configuring.

**Comment by robertgarrigos** [comment]
Or we could patch core upgrade to add an id column to roles
