### ISSUE TITLE
Theme to match Backdrop Seven/Basis

### ISSUE THREAD

**Issue by docwilmot** [backdrop-contrib/ubercart#133]
The order invoice pages are especially dated.

**Comment by docwilmot** [comment]
@robertgarrigos have tried to simplify the invoice pages and the checkout review page. The current design colors are very opinionated, with strong blue and grey themes which dont quite match the simplicity of Basis and Backdrop Seven. See screenshots below and let me know what you think. Its ready to PR.

** NEW Review page **
![review-page](https://user-images.githubusercontent.com/1042283/30267588-eeb39ebe-96da-11e7-8ffb-97d1ea8b9139.png)
** OLD (Drupal Bartik, same in Backdrop) **
![d7-order-review](https://user-images.githubusercontent.com/1042283/30268687-6825f726-96de-11e7-8a25-8c472f47dcbb.PNG)

** NEW Invoice page **
![invoice-page](https://user-images.githubusercontent.com/1042283/30267628-11c86060-96db-11e7-80d1-d5b0dce20fd1.png)
** OLD D7 **
![d7-invoice](https://user-images.githubusercontent.com/1042283/30268704-79c05a30-96de-11e7-8ef0-80895fbc3b15.PNG)

** Printable invoice **
![invoice-printable](https://user-images.githubusercontent.com/1042283/30267642-1b1c1e2c-96db-11e7-9ea4-68ef269f923a.png)

**Comment by docwilmot** [comment]
These are for Basis. Will tackle Bartik as well once I get some feedback.

**Comment by docwilmot** [comment]
Also pinging @klonos as our senior reviewer.

**Comment by robertgarrigos** [comment]
much better the new design. I like it :-)

**Comment by docwilmot** [comment]
Pushed a PR then.
