### ISSUE TITLE
Ubercart fails to install via project installer

### ISSUE THREAD

**Issue by jlfranklin** [backdrop-contrib/ubercart#164]
When trying to install Ubercart via the Install New Modules tab, the following error is returned:

Error installing Ubercart. The info file (temporary://update-extraction-02c54f33/ubercart/uc_store/uc_store.tests.info) does not define a 'type' attribute.

---
PR by @laryn : https://github.com/backdrop-contrib/ubercart/pull/184

**Comment by robertgarrigos** [comment]
Interestingly enough, if you download the tar.gz or zip, either from git or backdrop site, and do a manual installation, not just by uncompressing into the modules directory, but by uploading the compressed file with the manual installation form, in the Install New Modules tab, you don't get that error.

**Comment by robertgarrigos** [comment]
Could you please check whether this has been fixed with latest release? I guess I'm having cache issues and the installer is getting a previous release from backdrop site even it's labelled as the last one.

**Comment by robertgarrigos** [comment]
This error still persist in latest release :-(

**Comment by jlfranklin** [comment]
> This error still persist in latest release :-(

It is still broken here, too.

**Comment by robertgarrigos** [comment]
I've created a new release (1.x-1.0.2-beta) with all test.info files having a type = module line. Still the problem persists. I have no idea what's going on. And it is even funnier: if you try to do a manual install by giving the url you get the "no type" error. But if you download the zip file form github and do a manual install with it you get a "no name" error.

**Comment by docwilmot** [comment]
This may be because there isnt a `ubercart.info` file?

**Comment by jlfranklin** [comment]
Is there a requirement for there to be a module with the same name as the project name?  True, the most common case for modules is a single module with the same name as the project, (i.e., `<project name>/<module name>.info` where project name === module name), but there are a small number of modules in Drupal that don't do that.

**Comment by docwilmot** [comment]
I was implying that Installer or the Project Server may not be configured for that, hence the `no name`

**Comment by laryn** [comment]
The `.tests.info` issue should be fixed in core. https://github.com/backdrop/backdrop-issues/issues/1294

The Project Installer issue may be because of the unique way Ubercart is structured, with no `ubercart.info` (seems plausible, anyway). Here's an attempt to make it installable via Project Installer.

https://github.com/backdrop-contrib/ubercart/pull/184

Also, it might be good to update the branch and version to track the Drupal version we're coming from. (ie. branch `1.x-3.x` and next release `1.x-3.11.3-beta` or similar)

**Comment by laryn** [comment]
Just tested on a dev site after the latest release and the install works (requiring Rules, then EMW and Entity UI) and then fails with this error:

> Error: Call to undefined function uc_get_message() in uc_cart_install() (line 245 of /path/modules/ubercart/uc_cart/uc_cart.install).

Can we control the order that the submodules install in? It looks like `uc_store` should install before `uc_cart` -- maybe just switching them in the `.info` file would do it?

**Comment by laryn** [comment]
Just tested after the latest release and was able to install Ubercart on a fresh local sandbox through the Project Installer. The only weirdness was that it couldn't be enabled on the last step (I had to enable the ones I could, then go back to the main modules list to enable Ubercart).

![Screen Shot 2019-10-08 at 1 48 17 PM](https://user-images.githubusercontent.com/871421/66424126-a0b2ff00-e9d2-11e9-87bc-5083e1b6a228.jpg)

But that may be a core Backdrop issue more than an Ubercart issue. I'll close this issue under that assumption.
