### ISSUE TITLE
USPS shipping module not setting booleans correctly

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/ubercart#179]
I was trying to figure why the USPS shipping module wasn't returning any results and I think I've tracked it down.

In the `uc_usps.settings.json` config file, the following settings were causing the problem:

```
    "uc_usps_insurance": "FALSE",
    "uc_usps_delivery_confirmation": "FALSE",
    "uc_usps_signature_confirmation": "FALSE",
```

Manually editing to the following works:

```
    "uc_usps_insurance": 0,
    "uc_usps_delivery_confirmation": 0,
    "uc_usps_signature_confirmation": 0,
```

So somewhere in setting the boolean value it's actually storing it as text. I also ended up changing the default shipping type in a few places from `small package` to `small_package`. I'll do some testing and see if that is required as well, if so I'll PR those changes.

**Comment by laryn** [comment]
PR: https://github.com/backdrop-contrib/ubercart/pull/180

Further question: Are the options above intended to be disabled in the admin USPS settings? (I don't need them, but am curious if that was intentional):
![screen shot 2019-02-14 at 11 52 28 am](https://user-images.githubusercontent.com/871421/52806601-0838ca80-304f-11e9-87cb-59f9d8f40bbf.jpg)

**Comment by robertgarrigos** [comment]
> Further question: Are the options above intended to be disabled in the admin USPS settings? (I don't need them, but am curious if that was intentional)

Sorry, I don't know :-/

**Comment by robertgarrigos** [comment]
is this fixed, then?

**Comment by laryn** [comment]
Yes, it should be (with the exception of the question of the disabled options, but maybe we just leave those for now since we're not sure why they were disabled in the first place... It seems to have come from the Drupal version that way).
