### ISSUE TITLE
Ubercart Payment section appears above Admin in the List of Modules

### ISSUE THREAD

**Issue by EganSolo** [backdrop-contrib/ubercart#191]
This is disconcerting: Ubercart - Payment is listed before Admin section in the list of modules. See attached image. 
![payment_before_admin](https://user-images.githubusercontent.com/25394601/58592789-1ab1cb00-821e-11e9-8f54-7336b6791ec0.png)

**Comment by laryn** [comment]
Closing this since it's now part of the larger issue here: https://github.com/backdrop-contrib/ubercart/issues/225
