### ISSUE TITLE
Cyclical reference in ubercart modules. 

### ISSUE THREAD

**Issue by EganSolo** [backdrop-contrib/ubercart#192]
Ubuntu 14.04.6 LTS,  Apache 2.4.7 php 5.5.9, mysql 5.5.62, backdrop 1.13.1
----------------------------------------------------------------
The ubercart module which is part of the ubercart install depends on cart.
Cart, in turn, depends on ubercart.  In fact, ubercart depends also on ubercart...
Something's not right. See the attached images.
![cart_depends_on_ubercart](https://user-images.githubusercontent.com/25394601/58592932-8300ac80-821e-11e9-8af8-c43eac60d1e7.png)
![ubercart_depends_on_cart](https://user-images.githubusercontent.com/25394601/58592937-85630680-821e-11e9-9ee0-b4b8fd843f65.png)

**Comment by laryn** [comment]
I think you're right -- the core/required sub-modules should not be dependent on the umbrella `Ubercart` module, as this makes it impossible to uninstall as the dependencies cascade to each other.

@robertgarrigos, I think this was my fault in https://github.com/backdrop-contrib/ubercart/issues/163 where I was trying to make this visible to the Project Installer. I'll file a PR that removes those excess dependecies and if it looks good to you it should be an easy merge.

**Comment by laryn** [comment]
Or (feedback requested) should I rather revert the core/required submodule dependencies to what they were before. We need to make sure all the required modules get activated/depend on each other.

**Comment by laryn** [comment]
PR for testing: https://github.com/backdrop-contrib/ubercart/pull/193

**Comment by EganSolo** [comment]
Hi Laryn,
Please forgive my naivete, I'm new to Git hub :) 
Thank you for your fast response. Am I to understand from "PR for testing #193" that the module is ready to test? I'm happy to be a tester on this project since I need Ubercart to work as I transition from d7 over to backdrop. 
Thanks!

**Comment by laryn** [comment]
@EganSolo Glad to have you here and helping test/fix things! Now that you solved the EMW/Entity Plus thing locally, are you good to test the cyclical dependency issue too?

**Comment by laryn** [comment]
@EganSolo I made a new branch for this issue on my fork, which you can download here:
https://github.com/laryn/ubercart/tree/cyclical-192

*You may need to make sure to manually fix the EMWController edits after download this branch since those haven't yet been merged in.*

**Comment by laryn** [comment]
@EganSolo Checking in -- how's it going?

**Comment by laryn** [comment]
I think this is solved. Reopen if not.
