### ISSUE TITLE
config consistency in uc_product submodule

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-contrib/ubercart#2]
(Registering this bug for later fix)

uc_product creates node types for products and sets some variables for each one. Backdrop sets node type variables in node.type.<type>.json files thus uc_product should save their variables into the same node.type.<type>.json files. However, coder upgrade module started putting this variables into uc_product.settings.json file. I didn't want to change that and I kept migrating variable function the same way coder upgrade did, but I feel it should be changed.

**Comment by docwilmot** [comment]
I dont believe this is an issue. The data in the `uc_product.settings.json` files dont belong in the `node.type.json` files as far as I can tell as this data is specific to UC and wouldnt be used by any other modules referencing those files.
