### ISSUE TITLE
Trailing commas added where they shouldn't have been

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/ubercart#204]
This commit causes an issue:
https://github.com/backdrop-contrib/ubercart/pull/203/commits/766901082e88015acca13a6dba745dd0051db809

The trailing commas that were added cause an error because those aren't typical arrays (where the trailing comma is expected in coding standards) but are calls to `uc_address_format`.

**Comment by laryn** [comment]
PR for review: https://github.com/backdrop-contrib/ubercart/commit/9c96bfa66a681ecd1c47525ad019a5cc12f13a72

**Comment by klonos** [comment]
You are right @laryn ...merged.
