### ISSUE TITLE
Fatal error with Controller::save (PHP 7.2?)

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/ubercart#206]
I was installing on a fresh local install to test the latest commits and ran into a fatal error on installation. I'm not sure if it's due to PHP 7.2 or not.

Unfortunately I didn't copy the entire error down before I started debugging. It was essentially:

> Fatal error: Declaration of .. must be compatible with .. PHP

It seems the EntityPlus controller has an additional parameter for `save`.

**Comment by laryn** [comment]
PR for review:
https://github.com/backdrop-contrib/ubercart/pull/207

**Comment by klonos** [comment]
Thanks @laryn 👍 ...merged.
