### ISSUE TITLE
Warning after 1.14.1 update

### ISSUE THREAD

**Issue by and-e-h** [backdrop-contrib/ubercart#209]
Hi, updating to Backdrop 1.14.1 generates this warning message:

Warning: count(): Parameter must be an array or an object that implements Countable in _uc_line_item_list() (line 135 of /home/webserver/backdroptest/backdrop/modules/ubercart/uc_order/uc_order.line_item.inc).

---
PR by @laryn: https://github.com/backdrop-contrib/ubercart/pull/210

**Comment by laryn** [comment]
Thanks for the report. What version of Backdrop did you upgrade from? What version of Ubercart? Php?

**Comment by and-e-h** [comment]
Thanks for getting back to me laryn. I should have put that info in my post, sorry!

Debian 10
PHP 7.3.9
Backdrop 1.14
Ubercart 1.0.7-beta

**Comment by laryn** [comment]
@and-e-h I'll try to do some testing. Do you get the warning when doing a particular task or on a certain page?

**Comment by and-e-h** [comment]
I have only seen it after the Backdrop update page upon completion of the update process. There are a number of Ubercart modules I'm not using, so there may be something I'm not seeing.

**Comment by laryn** [comment]
@and-e-h Are you comfortable changing a file slightly and seeing if it solves it for you?

https://github.com/backdrop-contrib/ubercart/pull/210

**Comment by and-e-h** [comment]
Looks like that sorted out this issue. Just ran update.php on the test site and no sign of any warnings. Thanks laryn! :)
