### ISSUE TITLE
Rules 1.x-2.1.3 causes uc_payment_method_paypal_wps error

### ISSUE THREAD

**Issue by and-e-h** [backdrop-contrib/ubercart#211]
Latest Rules module update appears to break Ubercart payment methods conditions options page.

On Admin > Store > Payment Methods page, clicking on "conditions" generates the following error message:

Error
Call to undefined function rules_permissions_by_component()

--------------- 

My system:

Debian 10.2
Apache 2.4.38-3
MariaDB 10.3.18-0
PHP 7.3.11-1
Backdrop 1.14.2
Rules 1.x-2.1.3
Ubercart 1.x-1.0.7-beta

**Comment by laryn** [comment]
Taking a quick look here and I don't see code in this module that calls `rules_permissions_by_component()` -- do you have a more complete error/description including filename and line number?

**Comment by laryn** [comment]
@and-e-h You may want to follow the issue over here:
https://github.com/backdrop-contrib/rules/issues/55

I think this is a Rules issue, not Ubercart.

**Comment by and-e-h** [comment]
Thanks for taking a look, laryn. Thought it was Ubercart related because it only threw an error there, rather than elsewhere on my Backdrop site.
