### ISSUE TITLE
Default config needs tweaking: Product quantity field is not available on add to cart form

### ISSUE THREAD

**Issue by Egarbeil** [backdrop-contrib/ubercart#214]
When I try and check the optional quantity field on the add to cart form in Store - Configuration - Products, it wipes it out the minute I hit save.  There is no quantity available anywhere - what needs to be done to fix this?

<img width="816" alt="image" src="https://user-images.githubusercontent.com/41450710/73303855-21e20c00-41e5-11ea-8568-993b75221350.png">

**Comment by laryn** [comment]
@Egarbeil 
I just installed fresh on a sandbox and am not seeing this. It seems to work as expected in the admin settings as well as on the front end. What version are you running? (Maybe list version of Ubercart, Rules, and Entity Plus)

**Comment by Egarbeil** [comment]
Attached is a list of all modules installed and enabled.
[Modules-installed-vrsions.pdf](https://github.com/backdrop-contrib/ubercart/files/4125371/Modules-installed-vrsions.pdf)

Everything is up to date.  PHP version is 7.0.33.  MySQL is  10.0.38-MariaDB.

There is no custom code.

**Comment by laryn** [comment]
Any errors/info in the logs?

**Comment by Egarbeil** [comment]
Just this:  

 Warning: Illegal offset type in mailsystem_requirements() (line 21 of /home/path/public_html/modules/mailsystem/mailsystem.install).
 - Location:  admin/dashboard 

But I don’t think it’s related at all, although I don’t know where this is coming from.  

I don’t see anything else in the backdrop logs.

**Comment by laryn** [comment]
How about in the Javascript console? (Can you tell I'm grasping at straws a bit)

**Comment by Egarbeil** [comment]
Nothing.  No errors that I can find in javascript, ModSecurity, recent log messages, etc. It just won’t save the option.  I check them off, click save and then they disappear.   And the quantity field is not available.

It’s kind of urgent.  I have 3 clients going on backdrop now and 2 of them are e-commerce.  I need to get this working before the client notices it isn’t there.

Warmest regards,

Elisabeth Garbeil, MBA PMP
Brainwrap LLC
"Being on the web doesn't have to make your head hurt."
www.brainwrap.com
(810) 560-7181
egarbeil@brainwrap.com

**Comment by laryn** [comment]
Hard to say without more steps to reproduce (as mentioned, it's working on my sandbox), but here's a workaround you could try:

 - Go to **Configuration > Development > Configuration management > Single Import/Export > Export**
 - Select "Configuration" under "Configuration Group"
 - Select "Ubercart product settings" under "Configuration name"
 - Copy the configuration to a text editor

Here's mine from the sandbox where I was testing this:

```
{
    "_config_name": "uc_product.settings",
    "uc_product_image_widget": "",
    "uc_product_add_to_cart_qty": 1,
    "uc_product_update_node_view": 0,
    "uc_product_shippable_product": "1",
    "uc_image_product": "uc_product_image",
    "product-settings__active_tab": ""
}
```

Yours may look slightly different, but this the line to change on yours: 
`"uc_product_add_to_cart_qty": 1,`

Once you've changed that in the text editor, go to **Single import/export > Import** and paste the new config in there. Click "Import".

Voila?

**Comment by Egarbeil** [comment]
That did it!  

Here were my configuration settings:  
{
    "_config_name": "uc_product.settings",
    "uc_product_image_widget": "colorbox",
    "uc_product_add_to_cart_qty": false,
    "uc_product_update_node_view": false,
    "uc_product_shippable_product": "1",
    "uc_image_product": "uc_product_image",
    "uc_image_product_kit": "uc_product_image"
}

I changed "uc_product_add_to_cart_qty": false, to "uc_product_add_to_cart_qty”:1,

And imported. 

The check mark is now there and now so is the quantity box!  Thank you.


Warmest regards,

Elisabeth Garbeil, MBA PMP
Brainwrap LLC
"Being on the web doesn't have to make your head hurt."
www.brainwrap.com
(810) 560-7181
egarbeil@brainwrap.com

**Comment by Egarbeil** [comment]
Another stupid question (not related to this issue) ?  The images don’t appear in the cart view.


Warmest regards,

Elisabeth Garbeil, MBA PMP
Brainwrap LLC
"Being on the web doesn't have to make your head hurt."
www.brainwrap.com
(810) 560-7181
egarbeil@brainwrap.com

**Comment by laryn** [comment]
Could you open a new issue for that? I'll leave this one open for now and the maintainer can decide whether to leave it open or close it.

**Comment by Egarbeil** [comment]
Done.

Elisabeth Garbeil, MBA PMP
Brainwrap LLC
"Being on the web doesn't have to make your head hurt."
www.brainwrap.com
(810) 560-7181
egarbeil@brainwrap.com

**Comment by laryn** [comment]
Closed via https://github.com/backdrop-contrib/ubercart/commit/caa61ad12e1fa8cf42529bd2ecdcbadfcb40f94f
