### ISSUE TITLE
Ubercart is not creating needed image style(s) upon installation

### ISSUE THREAD

**Issue by Egarbeil** [backdrop-contrib/ubercart#215]
The product image (image field) does not show up in the cart view, but shows up in Add to Cart and product pages:  

<img width="1390" alt="image" src="https://user-images.githubusercontent.com/41450710/73790411-68e47a00-476e-11ea-862c-7a83214e9600.png">

All that shows up is a broken link symbol, but the image shows up just fine other places so it's not a broken link.

**Comment by laryn** [comment]
At a glance, it seems that Ubercart is not creating the image styles it is depending on (for new installations... upgrades probably retain them from when they were created on Drupal 7). 

@Egarbeil You could try creating an image style that has the machine name of `uc_cart` as a test -- style it however you like and then see if the cart picks it up.

**Comment by Egarbeil** [comment]
Laryn,

Thank you! That was it exactly.   This is a completely new installation, not a Drupal port and there were no ubercart image styles.  I created the uc_cart style and it showed right up.



Warmest regards,


Elisabeth Garbeil, MBA PMP
Brainwrap LLC
"Being on the web doesn't have to make your head hurt."
www.brainwrap.com
(810) 560-7181
egarbeil@brainwrap.com

**Comment by laryn** [comment]
Note for future, in case anyone wants to pick this up to attempt the fix:

[Image styles have been converted to CMI](https://api.backdropcms.org/node/41661) so `hook_image_default_styles()` no longer works and the image style definitions should be converted to CMI in this module's default config folder.

**Comment by laryn** [comment]
It looks like there are multiple image styles needed in various places:

- uc_thumbnail
- uc_product
- uc_product_full
- uc_product_list
- uc_cart
- uc_category

**Comment by laryn** [comment]
Closed with https://github.com/backdrop-contrib/ubercart/commit/dc937727a79b0de40f561e92c1b8c85e1eee2559
