### ISSUE TITLE
Entity Plus 1.0.4 breaks cart display

### ISSUE THREAD

**Issue by and-e-h** [backdrop-contrib/ubercart#216]
The following error message is displayed at http://localhost/cart

"Argument 1 passed to backdrop_attributes() must be of the type array, null given, called in /webserver/backdrop/modules/entity_plus/theme/entity_plus.tpl.php on line 33"

The error is clearly generated in the Entity Plus module, but Ubercart may also require updating. Rolling back to Entity Plus 1.0.3 stops the issue and displays the cart properly.

I'll repost this on the Entity Plus page.

System:
Debian 10.2
PHP 7.3.14-1~deb10u1
Backdrop 1.15
Ubercart 1.0.7-beta
Entity Plus 1.0.4

**Comment by laryn** [comment]
Fixing this in Entity Plus. Thanks for the report @and-e-h!
https://github.com/backdrop-contrib/entity_plus/issues/21
