### ISSUE TITLE
Compatibility with D7 ubercart modules?

### ISSUE THREAD

**Issue by MrByte** [backdrop-contrib/ubercart#217]
Are other Ubercart modules compatible with this Backdrop version?

**Comment by MrByte** [comment]
Or I guess more accurately, with Backdrop, without porting?

**Comment by laryn** [comment]
@MrByte Which modules are you referring to in particular?

**Comment by MrByte** [comment]
uc_stock_notify, feeds, a few others. I'd have to dig. Probably the wrong place to ask, this is more "Is Backdrop plug-n-play with D7 modules"

**Comment by laryn** [comment]
@MrByte You may want to ask particular questions on the Forum.
https://forum.backdropcms.org/

Here's the docs on porting modules:
https://api.backdropcms.org/converting-modules-from-drupal

And a contrib module that does a lot of the early work for you, if you plan to try porting a module yourself:
https://github.com/backdrop-contrib/coder_upgrade
