### ISSUE TITLE
Any estimated timeline or established milestones for a full Ubercart release?

### ISSUE THREAD

**Issue by jackaponte** [backdrop-contrib/ubercart#223]
My shop is considering building a new Backdrop site using Ubercart, but we're hesitant to use it in production without a full release. @robertgarrigos and other folks working on this project, do you have any estimated timelines, established milestones or other ways of projecting when a full release of this module might be made available? Are there any specific blockers that need to be addressed before a full release can be made? (There's a chance we might be able to help with some of that work at some point, depending on what needs to be done and how far along things are already!)

**Comment by robertgarrigos** [comment]
Sorry @jackaponte I haven't been working much with ubercart module lately. Thankfully, though, @laryn is becoming co-maintainer and I'm sure this will give a push to the PRs and a future release. Thanks @laryn to help on this!!

**Comment by laryn** [comment]
@jackaponte I don't have a specific timeline but here's what I'd see currently as a minimum before an initial full release _(recognizing that it's likely small easy-to-fix porting related bugs will be reported as people begin to use all the many sub-modules)_.  I've created a [1.x-3.x milestone](https://github.com/backdrop-contrib/ubercart/milestone/1) to gather tasks (we'll bump the version number to match Drupal 7's version when we have a full release). You or your team pitching in with PRs to get us there would be much appreciated.

### Easy to install and no fiddling needing to get basic functionality, no immediate confusion
- https://github.com/backdrop-contrib/ubercart/issues/215
- https://github.com/backdrop-contrib/ubercart/issues/162
- https://github.com/backdrop-contrib/ubercart/issues/218

### Easy to uninstall without leaving a mess behind
 - https://github.com/backdrop-contrib/ubercart/issues/208

### Current to Drupal 7 version, caught up on commits there
 - https://github.com/backdrop-contrib/ubercart/issues/176

### Other
- https://github.com/backdrop-contrib/ubercart/issues/224

**Comment by jackaponte** [comment]
Many thanks for these updates, @robertgarrigos and @laryn! Excited to hear that you'll be a co-maintainer, Laryn.

We've got one project coming up that might use Ubercart; if that's the path the client winds up taking, we'll certainly do what we can to contribute PRs or otherwise move things forward!

**Comment by laryn** [comment]
Closing this issue since we have an official milestone now to track the countdown to the full release, but feel free to chime in on any open issues.
