### ISSUE TITLE
Uninstall process review

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/ubercart#226]
Currently when uninstalling, you have to uninstall a lot of things one-by-one. For example, if you just install the core/required modules, then want to disable Ubercart, you have to disable each of these one step at a time:

 - Ubercart main module
 - Cart
 - Order
 - Product
 - Store

Likewise when you want to uninstall them, you have to do each one at a time.

Can that process be streamlined?

~~Also related but noted elsewhere (https://github.com/backdrop-contrib/ubercart/issues/208), some Views from Ubercart pollute the menu afterwards so those need adjustment to indicate they belong to the module and get removed when the module is uninstalled.~~

**Comment by laryn** [comment]
Related Zulip thread:

 - https://backdrop.zulipchat.com/#narrow/stream/218635-Backdrop/topic/Uninstalling.20submodules.20from.20the.20main.20module

**Comment by laryn** [comment]
This should be drastically simplified now per the two commits linked above.

**Comment by docwilmot** [comment]
Brilliant idea (didnt test but makes huge sense)
