### ISSUE TITLE
ipnp Paypal payment issue

### ISSUE THREAD

**Issue by and-e-h** [backdrop-contrib/ubercart#229]
Hi, just beginning to test the RC and hit this snag upon clicking Submit Order.

This is displayed on the https://ipnpb.sandbox.paypal.com/cgi-bin/webscr page....

"encrypted_cross_dispatch=dBj_5OZqrT0ylD0nfxaKBYoUgT6_o5ee6d9boXj5KLs7s2b7aVQ87DYNl9NgTwTAeK3QUMXitgFzepKANIS0vO4UQFU_27mayX1nAW"

The issue per old Paypal reports:

https://www.paypal-community.com/t5/PayPal-Payments-Standard/ipnpb-paypal-com-error-encrypted-cross-dispatch/td-p/1193332#

...and the address the uc_paypal.pages.inc points to at line 73 is "https://ipnpb.paypal.com/cgi-bin/webscr"

Backdrop 1.16.2
Debian 10.5 (Buster)
PHP 7.3.19-1~deb10u1
MariaDB 10.3.23

Looking forward to seeing this RC become final.

All the best, Andrew J. Howarth

**Comment by laryn** [comment]
Hmm... From the link above:

> So, the ipnpb URL is not correct for redirecting customer to PayPal in HTML forms as I mentioned, it is only used for IPN postbacks, which is a post processing procedure, so the documentation is correct. 

> ...you will still need to amend the PayPal button form that you have on your site so that it redirects customers to "https://www.paypal.com/cgi-bin/webscr" for the transaction flow. 

Looks like maybe I got a little over-eager with the ipnpb URL based on commits over in the D7 version. Specifically here:

 - https://github.com/backdrop-contrib/ubercart/blob/03400c063a591f3c1b31d0724a94a8ce88e82ee7/payment/uc_paypal/uc_paypal.install#L213-L224

@and-e-h , are you comfortable exporting **Configuration >> Ubercart Paypal settings** and then changing this line and re-importing?

`    "uc_paypal_wps_server": "https://www.sandbox.paypal.com/cgi-bin/webscr",`

Or resaving your Paypal settings and see if that does it? 

I think I may need to revert `uc_paypal_update_1001()` if that works...

**Comment by and-e-h** [comment]
Thanks for the quick reply Laryn.

Settings Exported, updated and Imported all works as expected now. :)
