### ISSUE TITLE
Error on changing product quantity in cart higher than Rules maximum

### ISSUE THREAD

**Issue by and-e-h** [backdrop-contrib/ubercart#231]
Hi, getting the following error if the quantity of a product in the Cart is updated and the new quantity is higher than the Maximum Product Quantity in Rules....

Error
Call to undefined function entity_property_verbatim_set()

Backdrop 1.16.2
Debian 10.5 (Buster)
PHP 7.3.19-1~deb10u1
MariaDB 10.3.23

**Comment by laryn** [comment]
Looks like that should be `entity_plus_property_verbatim_set` -- care to test and submit a PR?

**Comment by and-e-h** [comment]
Fix tested AOK and PR submitted @laryn :+1: 

https://github.com/backdrop-contrib/ubercart/pull/232

**Comment by laryn** [comment]
Thank you @and-e-h -- closed with https://github.com/backdrop-contrib/ubercart/commit/9fc0199b659e289fd45110db24587226db26122d
