### ISSUE TITLE
Migration Dependences

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/ubercart#235]
This is related to https://github.com/backdrop-contrib/ubercart/issues/225, but deals with the situation where we are migrating from a Drupal Ubercart installation.

The [migration instructions](https://backdropcms.org/upgrade-from-drupal) say to leave migrated modules enabled in Drupal when you generate the backdrop-read.sql db, so that the update hooks for those modules will be called and the modules will be left enabled after migration. However, the Backdrop version of Ubercart relies on three modules that don't exist in Drupal:

* Ubercart (ubercart)
* Entity Plus (entity_plus)
* Entity UI (entity_ui)

The result is that all the sub-modules of Ubercart (and any further dependencies) get disabled during the migration process, since the db doesn't know of their existence at the time that migration starts.

In order to keep the whole chain of dependent modules enabled, it works to create empty "stub" Drupal modules corresponding to those three Backdrop modules and enable them in the Drupal UI prior to migration, so that the migration process includes, in part:

* Install the 3 stub modules in Drupal;
* Enable them;
* Do whatever other preparation you need to do for migration;
* Generate the backdrop-ready.sql copy of the db;
* Remove the Drupal "stub" modules;
* Continue with the Backdrop migration per the instructions;
* Run update.php.

This appears to work nicely, resulting in a fully migrated and enabled Ubercart installation that matches what it was in Drupal (to the extent that the Backdrop sub-modules exist).

So, what I'm wondering is if it would be useful to distribute the three Drupal stub modules (each consisting of a Drupal .info file and an empty .module file) and a README as part of the Backdrop Ubercart distribution? Perhaps in a folder called `drupal_prep` or something like that? And maybe a hint for migration in the README file?

If that (or something like it) sounds reasonable, I'd be happy to put together a PR consisting of that. Or if there's a better way to handle the issue of keeping the Ubercart modules enabled during migration, would love to hear it. This was what worked for me.

**Comment by laryn** [comment]
@bugfolder Thanks for this -- it does sound like that would be generally useful for upgrades. Let me [pitch it out into the Zulip chat](https://backdrop.zulipchat.com/#narrow/stream/218635-Backdrop/topic/Ubercart.20upgrade.20question) and see if anyone else wants to chime in.

**Comment by bugfolder** [comment]
Per https://backdrop.zulipchat.com/#narrow/stream/218635-Backdrop/topic/Upgrade.20from.20D7, I'll add this information to the wiki.

**Comment by bugfolder** [comment]
...although the wiki doesn't allow file attachments, so we'll still need a way to make them available. For the moment, I'll attach them to this comment and then link from the wiki.
[entity_plus.zip](https://github.com/backdrop-contrib/ubercart/files/5318868/entity_plus.zip)
[entity_ui.zip](https://github.com/backdrop-contrib/ubercart/files/5318869/entity_ui.zip)
[ubercart.zip](https://github.com/backdrop-contrib/ubercart/files/5318870/ubercart.zip)

**Comment by olafgrabienski** [comment]
> the wiki doesn't allow file attachments

The Wiki seems to allow files but you "need to clone the wiki repo and edit it on your system", see https://gist.github.com/subfuzion/0d3f19c4f780a7d75ba2#how-do-i-add-files-to-a-wiki-page.

**Comment by laryn** [comment]
I'm going to close this for now, with a link to the Wiki page:

 - https://github.com/backdrop-contrib/ubercart/wiki/Upgrading-Ubercart-from-Drupal-7

Thanks @bugfolder!
