### ISSUE TITLE
Add rules to enable/disable stock level changes when editing orders

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/ubercart#236]
This is Drupal issue https://www.drupal.org/node/1034044. Details are there (see comments [11](https://www.drupal.org/project/ubercart/issues/1034044#comment-7421432) and [12](https://www.drupal.org/project/ubercart/issues/1034044#comment-7486800)), but the short version is: 

* The patch adds support for stock handling rules that handle more use cases than the default:

    * Added a new event, 'uc_order_product_updated', to uc_order, which fires on product changes in admin edited orders;
    * Added a new action, 'uc_stock_action_adjust_product_stock', to uc_stock, which updates stock levels based on changes in individual products;
    * Added a new default rule, 'uc_stock_adjust_on_product_change', to uc_stock, which connects the two.
    * Throughout uc_order and uc_stock, removed the direct stock manipulations that happened for edited orders and replaced them with firings of the 'uc_order_product_updated' event.
    * Gave all uc_stock-related rules the tag 'uc_stock' so that tag filtering in Rules is useful.

* The posted patch reproduces prior behavior, so it shouldn't break existing installs.
* Multiple sites are using it on D7.
* It's been languishing in the D7 issue queue for years with no action.

If y'all would be open to incorporating this into the Backdrop Ubercart, I'd be happy to turn the patch there into a PR here, but would like guidance from the maintainers if they're open to incorporating changes that haven't yet been accepted into D7 UC. (There's multiple patches in the D7 UC issue queue like this).

**Comment by laryn** [comment]
@bugfolder Yes, I'm definitely open to incorporating this. Especially if you're providing the PR. ;) My feeling is that D7 UC is moving fairly slowly at this point and we can feel free to add improvements here before they get added there (because they may never).

**Comment by laryn** [comment]
Thanks @bugfolder! I've merged this in, will be included in the next release.
