### ISSUE TITLE
Error when enabling credit card module

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/ubercart#238]
When enabling the separate `uc_stripe` module, it says it needs to enable `uc_credit`. When it tries to do so, it crashes with this error:

> Missing namespace in Config object name uc_credit. 

(This issue may be in `uc_stripe` if it is trying to access `uc_credit` config before it exists? If so I'll move it to that queue.)

**Comment by bugfolder** [comment]
Hey, I saw this error message in some recent Ubercart work. It happens when you do `config_set('mymodule', ...)` instead of `config_set('mymodule.settings', ...)`. (And indeed, this is happening in `uc_stripe.install`.) I'll post an issue over there.

**Comment by bugfolder** [comment]
Closing in favor of https://github.com/backdrop-contrib/uc_stripe/issues/7.
