### ISSUE TITLE
uc_attribute_update_1000() is missing $config->save()

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/ubercart#241]
In file `uc_attribute.install`, function `uc_attribute_update_1000()` is missing its `$config->save()` call, so that the attribute setting doesn't get brought over when upgrading a Drupal site.

This appears to be the root cause for https://github.com/backdrop-contrib/uc_price_per_role/issues/1.

I checked all the other Ubercart .install files, and this is the only one that's missing it in `hook_update_1000()`.

**Comment by laryn** [comment]
Thanks @bugfolder !
