### ISSUE TITLE
Image styles mixed up?

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/ubercart#242]
I just installed Ubercart for the first time (since Drupal 6 I believe!) on a new Backdrop site (not an upgrade). Liking it so far!

One issue I've noticed is that two of the image styles seems to be mixed up:

![image](https://user-images.githubusercontent.com/2385329/100403836-01f4d080-30b4-11eb-9e4d-657a43f0e77c.png)

![image](https://user-images.githubusercontent.com/2385329/100403865-18029100-30b4-11eb-8ec9-4d84543e6bb4.png)

I.e. the 'full' image is scaled to 250px while the regular image is not.

Also, once this is fixed, I think the 'full' image shouldn't have any effects at all. Currently there's a 'Scale height' effect with no values, which looks wrong...

**Comment by ghost** [comment]
I manually changed the styles on my site, and here are their new config files, if that helps:

```json
{
    "_config_name": "image.style.uc_product",
    "label": "Product image",
    "name": "uc_product",
    "storage": 4,
    "module": "uc_product",
    "effects": {
        "2": {
            "name": "image_scale",
            "data": {
                "width": "250",
                "height": "250",
                "upscale": 0
            },
            "weight": "2"
        }
    },
    "overridden": true
}
```

```json
{
    "_config_name": "image.style.uc_product_full",
    "label": "Product full image",
    "name": "uc_product_full",
    "storage": 4,
    "module": "uc_product",
    "effects": [],
    "overridden": true
}
```

**Comment by bugfolder** [comment]
Yes indeed, they're switched. Here's the relevant bit from D7 Ubercart showing what they should be:
```
function uc_product_image_default_styles() {
  $styles = array();

  $styles['uc_product'] = array(
    'effects' => array(
      array(
        'name' => 'image_scale',
        'data' => array(
          'width' => '250',
          'height' => '250',
          'upscale' => 0,
        ),
        'weight' => '0',
      ),
    ),
  );

  $styles['uc_product_full'] = array(
    'effects' => array(),
  );
  ...
```
Good catch, thanks! PR to come.
