### ISSUE TITLE
Deleting class doesn't allow deleting content type

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/ubercart#243]
I created a product class which created a matching content type. When I later deleted the product class, it said something about unlocking the content type (can't remember the wording, but I thought it implied that the content type would still be there but I'd be able to delete it too). However even after clearing caches and running cron, the content type can't be deleted.

I looked into it and compared this content type with a regular one that could be deleted. I found that the only difference was the config file for that content type had `"module": "uc_product",`, whereas others have `"module": "node",`. Changing `uc_product` to `node` is what finally allowed me to delete the content type.

I recommend seeing if it's possible to do the automatically so that users have more control over product-created content types after deleting the product class.

**Comment by ghost** [comment]
Did it again and took notice of the message this time. It says:

> The node type associated with this product class will revert to a standard node type.

But obviously that's not the case since standard node types can be deleted...

**Comment by laryn** [comment]
Good point, the node type's `module` config entry should be reverted to `node` when a product class is deleted. 

Something like `config_set('node.type.classname', 'module', 'node');` in the right spot should do it, it sounds like.

**Comment by djzwerg** [comment]
Hi. Is there any work on this issue?

**Comment by bugfolder** [comment]
There will be now. Should have a fix in soon.

**Comment by bugfolder** [comment]
I'm going to merge the PR because the current PR seems to address the problem, but @djzwerg, if you can describe a procedure that still reproduces the problem after the merge (and new release) ([see this comment on the PR](https://github.com/backdrop-contrib/ubercart/pull/392#issuecomment-1320996226)), please do reopen this issue and add the procedure in a comment.

**Comment by djzwerg** [comment]
@bugfolder I'm going to try a new test with a vanilla BD and UC. I don't know what could be the reason because I've installed a few other modules, e.g. product kit.
