### ISSUE TITLE
Display image widget options

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/ubercart#245]
![image](https://user-images.githubusercontent.com/2385329/100506448-330ef700-31c1-11eb-8823-e94465fb2c84.png)

Different image widgets are available if you install certain other modules that Ubercart integrates with. However they're not listed here. I recommend adding a message here so people know what module(s) they need to download in order to use this functionality.

**Comment by bugfolder** [comment]
Ubercart provides built-in support for Colorbox, Thickbox, and Lightbox2 modules (see `uc_store_uc_image_widget()`), However, only Colorbox has been ported to Backdrop.

It's still worth pointing out Colorbox's existence in this message, something like this:

![colorbox](https://user-images.githubusercontent.com/29214084/196841541-06ecdbee-5fd0-4720-83ab-ce19d2714345.jpg)

I've put together a PR that anticipates the availability of all three, but commented out the lines for Thickbox and Lightbox2, with the idea that we'd uncomment those when/if their respective modules get ported.

(Incidentally, any module that implements `hook_uc_image_widget()` gets listed in the radio button option list.)

PR to follow.

**Comment by bugfolder** [comment]
Per a recent Zulip discussion ("Colorbox module alternatives"), other similar image widgets in Backdrop include [Featherlight](https://backdropcms.org/project/featherlight), [PhotoSwipe](https://backdropcms.org/project/photoswipe), and [GLightbox](https://backdropcms.org/project/glightbox).

Conversely, Thickbox isn't even a D7 module, so will likely never become a Backdrop module and so should be expunged entirely. And [D7 Lightbox2](https://drupal.org/project/lightbox2) is pretty complex, so, given other Backdrop alternatives, it may not get to Backdrop for a while, if ever.

So, putting this issue back to "in progress", to more thoroughly accommodate the current and anticipated future state of image widget modules in Backdrop.

**Comment by bugfolder** [comment]
I've added Featherlight and GLightbox in addition to Colorbox. PhotoSwipe isn't as good of a fit; for example, one must define all image dimensions for Photoswipe, but the callbacks used by UC don't pass that back and forth. Users will have a choice of three image widgets, so I think that's reasonable (Colorbox has 516 installs already), and there's always the option for someone to add others by implementing `hook_uc_image_widget()`.

So I'll call this one ready to test and review.

**Comment by bugfolder** [comment]
@argiepiano, care to take a look at this when you get a chance?

**Comment by argiepiano** [comment]
@bugfolder, thanks for providing the PR. It works for me, but I do have a question: I noticed you are using `hook_init` to load the glightbox libraries. This seems to me slightly inefficient (hook_init is invoked on every page request, so the `if` statement will always be evaluated).

I'm wondering if it may be more efficient to just load the libraries inside `uc_store_image_widget_glightbox()`? This is called by `theme_uc_product_image()` when theming a product image, and when Glightbox has been selected as the formatter.  

This approach would be similar to the one used by the Glightbox formatter for "regular" image fields: it loads the libraries and settings within `theme_glightbox()` - i.e. its theming function.

**Comment by argiepiano** [comment]
Thinking more about this - perhaps you are using `hook_init()` to assure that the libraries are still loaded when cached nodes are viewed? I haven't tested this scenario, but it makes sense. Still, wondering if a different hook may be more appropriate, like `hook_node_view()` and then using `uc_product_is_product()` to check that the loading node is a product. I believe `hook_node_view()` is invoked even when viewing cached nodes.

**Comment by bugfolder** [comment]
> Thinking more about this - perhaps you are using hook_init() to assure that the libraries are still loaded when cached nodes are viewed?

Umm, yes, sure, that's exactly what I was thinking! Always thinking two steps ahead, that's me!

No, actually, I was two steps behind; I used `hook_init()` just to make sure it was loaded if it was going to be needed sometime; hadn't actually thought about trying to load it only when it was specifically needed. I'm sure I would have forgotten about cached nodes if I'd gone down that path.

**Comment by argiepiano** [comment]
@bugfolder I've done some testing. Loading the libraries in `uc_store_image_widget_glightbox()` works well. Even when the node entity is cached, the field formatter (uc_store_image_widget_glightbox()) is still called. And in the case of an anonymous visitor, Backdrop serves full cached pages that include all the needed js.

So, we can eliminate `uc_product_init()` and change  `uc_store_image_widget_glightbox()` to:

```php
/**
 * Generates the GLightbox-specific HTML attributes.
 */
function uc_store_image_widget_glightbox($rel_count) {
  $module_path = backdrop_get_path('module', 'glightbox');
  backdrop_add_library('glightbox', 'glightbox', FALSE);
  backdrop_add_js(array('glightbox' => config_get('glightbox.settings')), 'setting');
  backdrop_add_js($module_path . '/js/glightbox.js');
  backdrop_add_css($module_path . '/css/glightbox.css');
  if (!is_null($rel_count)) {
    $img_index = 'uc_image_' . $rel_count;
  }
  else {
    $img_index = 'uc_image';
  }
  return ' class="glightbox" rel="' . $img_index . '" data-gallery="single-image"';
}
```

Notice that the `if` statement in the original PR is not needed, because this theming/formatting function is only called when rendering a field that uses the Glightbox formatter.

**Comment by bugfolder** [comment]
Yes, this works great (and is, of course, both more efficient and direct). PR updated.

(Getting towards time to do another UC release. Perhaps in concert with B's 1.25.0 release?)

**Comment by argiepiano** [comment]
RTBC!

Eventually, it may be a good idea to move the selection of the image "widget" (which, in fact, it's a formatter, not a widget) to the field formatter configuration in Manage display, when the user chooses the "Ubercart product" formatter. That way, the selection of the actual plugin is done right there rather than having to go to the Store menu.
