### ISSUE TITLE
Operations could be drop buttons

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/ubercart#246]
To make this more Backdroppy, the operations could be converted to drop buttons:

![Screen Shot 2020-11-30 at 12 31 15 PM](https://user-images.githubusercontent.com/871421/100650079-07972400-3309-11eb-8672-cea075ee988a.jpg)

Locations:
 - Product Classes
 - Countries and Addresses: admin/store/settings/countries
 - Features: node/%/edit/features
 - Other?

**Comment by bugfolder** [comment]
A search for the string `Operations` (the typical column header) turns up the following pages and their functions:

* admin/store/products/classes (function `uc_product_class_default()`)
* admin/store/settings/countries/import (function `uc_country_import_form()`)
* node/%/edit/features (function `uc_product_features()`)
* admin/store/products/attributes (function `uc_attribute_admin()`)
* admin/store/products/attributes/1/options (function `theme_uc_attribute_options_form()`)
* admin/store/reports/stock (function `uc_stock_report()`)
* admin/store/settings/taxes (function `uc_taxes_admin_settings()`)
* admin/people/expiration (function `uc_roles_expiration()`)

PR to follow shortly.
