### ISSUE TITLE
Content type Product shippable option

### ISSUE THREAD

**Issue by amilenkov** [backdrop-contrib/ubercart#247]
Hello,

In the product type settings Product there is an option "Product and its derivatives are shippable" with a check mark.

At admin/structure/types/manage/product - Ubercart product settings

This check mark cannot be deactivated, even when disabling a check mark and saving the content type when reopening the content type, this setting remains checked.

It is possible to deactivate this only in the individual pages of the Product type, but when all the products in the store are not shippable, it is annoying to deactivate when creating each product.

Since I haven't worked with Ubercart for a long time, I did a test installation of Ubercart 7.x-3.13 with Drupal 7 for comparison and there it works normally and "Product and its derivatives are shippable." are deactivated without any problems in the Product content type settings.

**Comment by laryn** [comment]
Thanks @amilenkov -- this should fix it. https://github.com/backdrop-contrib/ubercart/commit/6a982a4b265020181f25c5985c00586cdebff3bf

**Comment by amilenkov** [comment]
@laryn 

I wasn't sure how to use 6a982a4 and did the following:

I went to l GitHub on backdrop-contrib / ubercart and downloaded ubercart-1.x-3.x.zip.

I unzipped from this atchive the file uc_product.module and via FTP replaced the existing file uc_product.module in the uc_product folder of the Ubercart in my Backdrop test installation (there is an ubercart-1.x-3.13.0-rc2 installed).

Now "Product and its derivatives are shippable" check mark works properly, is saved to the content type and nodes for new products are created with this option turned off by default, what I was trying to do.

I hope this will not change with the next standard upgrade of the module with new versions from www.backdropcms.org/modules

Thank you very much for the quick expert assistance.

I like Ubercart and I think it is a great solution for an online store for small businesses, but unfortunately it is very difficult, almost impossible to find educational information - guide or book haw to use Ubercart.

The help pages on Drupal's site are incomplete and outdated (in many of them it is clear from the text that they were written before Ubercart used Rules instead of Conditional actions, the Ubercart site - www.ubercart.org does not work at all and there was not only a lot of help information, but also modules with good systematization and categorization.

So now I study how Ubercart works with trial and error, I make purchases, I check what the different settings do, I experiment.

I'm not a programmer, but I can write texts and I understand from teaching. I'm ready to help by creating help information for Ubercart but I don't know how and where to do it.

And I believe that the successful development of Ubercart is key to the widespread use of Backdrop by small businesses.

**Comment by laryn** [comment]
@amilenkov Thanks for verifying -- this fix will be included in the next release so no need to keep patching after upgrades.

I appreciate your offer to write documentation. That will be a great help! I think it makes sense to add and edit pages in the Wiki:

 - https://github.com/backdrop-contrib/ubercart/wiki

If there is any valuable information on the old (defunct) ubercart.org site, some of it may be accessible via archive.org to pull out and add to the Wiki:

 - https://web.archive.org/web/2019*/ubercart.org
