### ISSUE TITLE
Bank Transfer Payment for Ubercart

### ISSUE THREAD

**Issue by amilenkov** [backdrop-contrib/ubercart#248]
Hi,

I'm not sure where to post this, but since it's a payment method module for Ubercart - I write about this here. Also because I think this will be a useful addition to Ubercart for Backdrop for many people and online stores.

This is about Bank Transfer | Ubercart Payment

https://www.drupal.org/project/uc_bank_transfer

I don't have enough knowledge needed to fully convert a module from Drupal 7 to Backdrop, but I downloaded Bank Transfer's 7.x-1.0-beta1 and edited the info file as required by Backdrop tutorials.

First edition of .info file:

type = module
name = Bank Transfer
description = Provides the Bank Transfer payment method.
dependencies[] = cart
dependencies[] = uc_payment
package = "Ubercart - payment"
backdrop = 1.x

The module is activated and set up successfully, but every time the list of active modules is edited or even re-saved, the modules form displays a message that it is necessary to activate the Cart module before activating Bank transfer.

However, the Ubercart for Backdrop module group lacks a Cart module, but has an Ubercart module. 

So I did a second edition of the .info file:

type = module
name = Bank Transfer
description = Provides the Bank Transfer payment method.
dependencies[] = ubercart
dependencies[] = uc_payment
package = "Ubercart - payment"
backdrop = 1.x

In this version of .info file, without any other changes, the Bank transfer module works with Backdrop's Ubercart module without any visible problems. At least in my test installation.

Therefore, I believe that it is possible, after this work has been reviewed by a professional Backdrop specialist, the Bank Transfer module | Ubercart Payment to be added to Ubercart's payment methods officially with minimal effort.

Note:

I also tried and converted  Bank Transfer with Coder Upgrade - but the processing in this way of Bank Transfer led to errors and the module did not work in Backdrop. The manual editing as above second edition of the .info file made the module work in Ubercart, but I don't know if more work need to be done in other files and code in accordance with Backdrop programming standards.

**Comment by djzwerg** [comment]
+1 for this feature request. Is it possible to provide your code @amilenkov to test and maybe support the development?

**Comment by amilenkov** [comment]
I confirm that I am interested in the Drupal 7 Bank Transfer payment conversion for Backdrop CMS. But I can't add anything more than what was written above. This was a simple text edit of the .info file. Optimal conversion for Backdrop CMS requires a comprehensive code review from the Backdrop standards perspective, which I can't do because I'm not a programmer.

I have created and maintain several websites with Backdrop and Ubercart in Bulgarian and I am very pleased with the development of Ubercart as a Backdrop platform for e-commerce - the last months and years I have seen significant success.

Bank Transfer payment in my practice is required as an option for orders from business customers who wish to pay by bank Transfer. I have currently found a solution to this issue through comments to the order, where the customer states a desire to pay by bank transfer and the bank account is further negotiated through e-mail contacts.

**Comment by bugfolder** [comment]
I took a look at the code of the Drupal module. It does need some work to handle the conversion of `variable_get()`/`variable-set()` to config. This is something that's done automatically by `coder_upgrade` module, but that conversion can leave some loose ends that need manual cleanup. I'll take a deeper look into this over the next several days.

**Comment by argiepiano** [comment]
This port looks pretty straightforward. One aspect to check is the token handling of the module - checking if it works as expected when/if Entity Tokens is enabled.

**Comment by argiepiano** [comment]
After checking with @bugfolder, I have ported the module Ubercart Bank Transfer. Initial release available [here](https://github.com/backdrop-contrib/uc_bank_transfer/releases/tag/1.x-1.0.0-beta).

Please test and post any issues directly in the module's issue queue.

**Comment by amilenkov** [comment]
You are perfect! Thank you very much friends!
Today I started working on a new site with Backdrop and Ubercart and I can't wait to try uc_bank_transfer in practice too. Will report back.

I'm very sorry that I'm not a programmer and can't do this job, but I'm willing to help the Backdrop community to the best of my ability - the Backdrop header banners for Facebook, YouTube and Twitter were made by me as final designs, although initial ideas were submitted by another community member as a sketch 5-6 years ago.

**Comment by bugfolder** [comment]
Looks like this issue has been solved. (Thanks @argiepiano!). Closing this issue.
