### ISSUE TITLE
Clean up config implementation

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/ubercart#249]
There's no `uc_authorizenet_config_info()`. This prevents using configuration sync, because the synchronizer complains that no one owns the file `uc_authorizenet.settings.json`.

It's a simple fix. I'll prepare a PR.

**Comment by laryn** [comment]
Thank you @bugfolder! Would you be willing to spot check submodules to see if any others are missing `hook_config_info()`? If so we can get them all at once...

**Comment by bugfolder** [comment]
I did a quick search, looking for `_config_name` (sign of a config file) and for `hook_config_info` (sign of its implementation) and comparing. I didn't find any other missing declarations of `uc_*.settings.json` config files, but there are several other config files that aren't declared in the `hook_config_info()` implementation, for example,

* `image.style.uc_cart` (and some other images styles)
* `views.view.uc_catalog_terms` (and a bunch of other Views config files)

If I'm understanding the config system correctly, these, too, should be declared in `hook_config_info()` so that they'll be removed properly when/if the module is uninstalled. Is this correct?

**Comment by laryn** [comment]
Ah, you may be right! If so, we can chop out some of the manual work I added when I took over and was trying to get a cleaner install/uninstall process, e.g.:

 - https://github.com/backdrop-contrib/ubercart/blob/1.x-3.x/uc_order/uc_order.install#L707-L713

**Comment by bugfolder** [comment]
OK, I'll go through & update all the affected `hook_config_info()`'s and will chop the no-longer-needed uninstall code in the PR.

**Comment by bugfolder** [comment]
It looks like there's 4 kinds of edits needed (which I'm working through) in the general area of config and install:

* Put the missing declarations into `hook_config_info()` (not that many missing; the Views were already present);
* Remove superfluous `variables` deletions and config deletions from `hook_uninstall()`, since the `variables` variables were deleted in `hook_upgrade_1000()` and the configs get deleted automatically on uninstall if they're declared in `hook_config_info()`;
* Remove empty `hook_install()`, `hook_uninstall()` functions;
* Correct the first line of the `hook_update_N()` docblock to describe what it does, rather than `Implements hook_update_N().` (per [coding standards](https://docs.backdropcms.org/doc-standards)).

These are all kinda related, so I'm planning to put them all into the revised PR, unless you would prefer them broken up.

**Comment by bugfolder** [comment]
I did run into something as I was testing installation/uninstallation. Removing `uc_product` or `uc_product_kit` leaves behind content types and potentially product nodes. Should the nodes and content types be removed upon uninstallation of their respective modules?

**Comment by laryn** [comment]
I think it's fine to clean all this up in one PR.

As far as nodes and content types, it's a good question. Let's move that to a separate issue and we can compare what D7 does and make a decision separate from this clean up.

**Comment by bugfolder** [comment]
Sounds good. updates pushed to [the PR](https://github.com/backdrop-contrib/ubercart/pull/250). I'll open a new issue for the content types and nodes.

**Comment by laryn** [comment]
Thanks for all that clean up work @bugfolder!
