### ISSUE TITLE
`uc_product_type_names()` leaves Product Kit blank

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/ubercart#252]
`uc_product_type_names()` doesn't include a name for type 'product kit' when the Product Kit module is enabled. They key is there, but the value is blank.

In the current implementation of `uc_product_type_names()`, the names are collected by invoking `hook_node_info()` for all products. The Product Kit doesn't implement that hook, hence no name. So one solution would be to add an implementation. However, the documentation for `uc_product_node_info()` says

```
 * Deprecated in Backdrop. See uc_product.install.
 * // TODO delete this function when not needed any more
 * because it is also called directly by uc_store module to create product classes.
```

So instead of relying on `hook_node_info()`, we can get the product name from `node_type_get_types()`, which is what I've done in the PR to follow. Also used static variables to make multiple calls less expensive.

**Comment by bugfolder** [comment]
PR https://github.com/backdrop-contrib/ubercart/pull/253

**Comment by laryn** [comment]
Thanks @bugfolder -- looks great!
