### ISSUE TITLE
D7 Upgrades: Can we automatically enable requirements in some cases?

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/ubercart#255]
See:

 - https://github.com/backdrop-contrib/entity_plus/issues/47

**Comment by laryn** [comment]
If you find yourself in this situation, a workaround is to use the Config import functionality at **/admin/config/development/configuration/single** to import the four views manually:

 - https://github.com/backdrop-contrib/ubercart/blob/1.x-3.x/uc_product/config/views.view.uc_products.json
 - https://github.com/backdrop-contrib/ubercart/blob/1.x-3.x/uc_order/config/views.view.uc_customers.json
 - https://github.com/backdrop-contrib/ubercart/blob/1.x-3.x/uc_order/config/views.view.uc_orders.json
 - https://github.com/backdrop-contrib/ubercart/blob/1.x-3.x/uc_order/config/views.view.uc_orders_user.json

**Comment by bugfolder** [comment]
As of Backdrop 1.22.0, required modules (like Entity Plus) are now automatically enabled during an upgrade. See https://github.com/backdrop/backdrop-issues/issues/5499.
