### ISSUE TITLE
USPS endpoint HTTP to HTTPS

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/ubercart#256]
I was going to file this here and in the D7 queue, but I see that @morbus has beat me to it over there (and they've provided the simple patch that will work here as well). I'll submit their patch as a PR here and respond in that thread as well.

 - https://www.drupal.org/project/ubercart/issues/3204554

**Comment by laryn** [comment]
This was simple enough that I just committed directly. Thanks @morbus!

@bugfolder The old USPS endpoint stops working around June 26 so it would be good to make another incremental release by early June at the latest, just in case you have anything you'd like to get in before then. :)

**Comment by bugfolder** [comment]
@laryn Thanks, yes, I've got a few (including one or two D7 bugfix patches that have languished in D7-world for years, despite passing tests and multiple WFMs). I'll submit them as new issue/PRs.

**Comment by morbus** [comment]
👍🏻
