### ISSUE TITLE
Users can manipulate order details after completing checkout

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/ubercart#257]
Caught my eye in the D7 queue:

> <h3 id="summary-problem-motivation">Problem/Motivation</h3>

> This is based on @antongorodezkiy's testing from issue <a href="https://www.drupal.org/project/ubercart/issues/1597154#comment-13981103">1597154</a>.

> It is possible for users to manipulate order information after successfully completing checkout.

> <h4 id="summary-steps-reproduce">Steps to reproduce</h4>

> <ol>
>   <li>Enter the checkout page on one tab/window.</li>
>   <li>Open a 2nd tab/window and enter checkout as well. Complete the checkout process.</li>
>  <li>Go back to the 1st tab/window and update the delivery, billing, or shipping options and trigger ajax in some way.</li>
>  <li>The completed order's details will change.</li>
> </ol>

> <h3 id="summary-proposed-resolution">Proposed resolution</h3>

> Check if the order has already completed and exit out of the checkout page without updating the order.

[There is a patch available in the issue](https://www.drupal.org/node/3196363).

**Comment by laryn** [comment]
I have not verified that this affects the Backdrop version but I would assume so.

**Comment by bugfolder** [comment]
>  I have not verified that this affects the Backdrop version but I would assume so.

I have, and it does. Working on the fix.

**Comment by bugfolder** [comment]
I can confirm that the patch fixes the problem. Upon attempting the second checkout, after clicking "Review order," I am returned to the shopping cart page `cart`, with the normal message "There are no products in your shopping cart."

There is no warning message or explanation, but I don't think one is necessary, since this would only happen to someone who is trying something hinky. So I think the D7 patch is sufficient.

**Comment by argiepiano** [comment]
Agreed!

**Comment by laryn** [comment]
Looks good to me! I am happy to merge but if someone gets to it before me, it would be nice to include credit to anyone on the D7 side who contributed to reporting/discussing/fixing the issue (there are two related threads on D7):

 - https://www.drupal.org/project/ubercart/issues/1597154#comment-13981103
 - https://www.drupal.org/project/ubercart/issues/3196363

**Comment by bugfolder** [comment]
Maybe leave this unmerged until just before the next release, and then this comment can be a reminder to manually add that credit to the auto-generated release notes for the next release—which should probably bump the minor number if it includes all the items currently with RTBC or MRR labels. (Should we pick a target date for the next release? Same as Backdrop 1.24.0?)

**Comment by laryn** [comment]
Sounds great.
