### ISSUE TITLE
Implementations of hook_variable_info() now superfluous?

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/ubercart#262]
Ubercart modules uc_quote, uc_cart, uc_stock, and uc_store all contain implementations of `hook_variable_info()` and related hooks. These are all hooks supported by the [Drupal 7 Variable module](https://www.drupal.org/project/variable).

There is no Backdrop version of this module. The D7 version was last updated in 2014 and there is no D8/9/etc. version. (There are, however, 176,356 sites currently using the D7 version.) The two documentation pages listed on the module page,

* http://drupalcode.org/project/variable.git/blob/refs/heads/7.x-1.x:/variable.api.php
* http://drupalcode.org/project/variable.git/tree/refs/heads/7.x-1.x:/includes

lead to 404s. No issue has been updated in over a year.

Since that module does not seem to be under active development/support, there is no Backdrop version of the module, and so no way to even test the hook implementations, should we keep the hook implementations? Or are they now unnecessary cruft?

**Comment by laryn** [comment]
Good question. I suppose we can take them out and assess whether to put them back in later when (if) a need arises?

For reference, the current documentation links can be found here:

 - https://git.drupalcode.org/project/variable/-/blob/7.x-2.x/variable.api.php
 - https://git.drupalcode.org/project/variable/-/tree/7.x-2.x/includes

**Comment by bugfolder** [comment]
Seems reasonable. PR to remove the superfluous files to follow.
