### ISSUE TITLE
Entity keys declarations

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/ubercart#274]
I see the following warning while testing Reference:

>  The Cart item entity type has not declared its label attribute and cannot be referenced.
>  The Order entity type has not declared its label attribute and cannot be referenced.
>  The Order product entity type has not declared its label attribute and cannot be referenced.

This appears to be referring to the `entity keys` declaration, which may just need `'label' => 'label',` added to it. 

e.g. https://github.com/backdrop-contrib/ubercart/blob/d0cb2ae6e6a08a439e98cebbd4fa9f82b8c2560c/uc_order/uc_order.module#L438-L440

@bugfolder Does that sound right/okay to you? I'll file a PR if so.

**Comment by bugfolder** [comment]
According to [`hook_entity_info()`](https://docs.backdropcms.org/api/backdrop/core%21modules%21entity%21entity.api.php/function/hook_entity_info/1), `label` is not listed as a key for `entity_keys`, and a quick search through core didn't turn up any `'label' => 'label'` in any of the core implementations of `hook_entity_info()`. Which makes me wonder about this solution. Did it fix it? (Is 'label' required but undocumented?)

Did you see this during one of the unit tests of Reference module, or something else?

**Comment by laryn** [comment]
I had the same notification with Paragraphs and I did it there as a test -- it did make the warning go away. Maybe it's not required in general, but just for Reference?

https://github.com/backdrop-contrib/reference/blob/24cb2a4304fe51443f75799bb00c7dcf8e3f0063/reference.module#L73-L86

Since Reference is slated for core in the future I was doing some testing and these warnings show up when editing a Reference field -- with Paragraphs and these three, it felt like something that should be addressed in one way or another. Perhaps the problem is with Reference displaying this warning so prominently...

![entity-keys-warning](https://user-images.githubusercontent.com/871421/120034322-858b6d80-bfc2-11eb-9290-3877f625b830.png)

**Comment by bugfolder** [comment]
Looks like it's this issue (and your proposed solution is the right one). Also needs `status` key.

https://github.com/backdrop/backdrop-issues/issues/3103

**Comment by laryn** [comment]
Actually looking at the code I linked above, I'm guessing it's a bug in Reference.

```
// Ensure that the entity type has registered its label entity key.
if (isset($entity_type_info['entity keys']['label'])) {
   $entity_type_options[$entity_type] = $entity_type_info['label'];
} else {
   backdrop_set_message(t("The @entity entity type has not declared its label attribute and cannot be referenced.", array('@entity' =&gt; $entity_type_info['label'])), 'warning');
}    
```

The code inside the `if` references `$entity_type_info['label']` instead of `$entity_type_info['entity keys']['label']`...

**Comment by laryn** [comment]
Ah, good find!

**Comment by bugfolder** [comment]
And backdrop core needs an issue to add these keys to the documentation of `hook_entity_info()`.

**Comment by docwilmot** [comment]
I think the code in Reference is actually correct, but unnecessary. In D7 Entity you needed a way to know how to find an Entity's label, so for Node it would be `title`, or for comments, `subject`, so that you could say in code `$node->title` or  `$comment->subject`. But in Backdrop all our Entities are classed objects, and all *must* have a `Entity::label()`, hence we dont any longer need a `label` key in the `entity keys`. For any Entity in Backdrop you can call `$entity->label()` without knowing if the label is stored in `subject` or `title` etc, so `$node->label()` is the same as `$node->title`

So that `if...else` code block shouldnt be necessary I think. Labels are everywhere.

**Comment by laryn** [comment]
@mikemccaffrey Do you agree with @docwilmot 's point above? Is that code in Reference irrelevant at this point?

**Comment by laryn** [comment]
Let's close this one for now...
