### ISSUE TITLE
The Image file field is not being created for products 

### ISSUE THREAD

**Issue by robnacnamha** [backdrop-contrib/ubercart#278]
After installing and enabling latest ubercart module release 1.x-3.13.0 In the status report (please see screenshot) I'm told that the image field has not been created for products. When I click the link above to automatically configure image support for the image file field I'm taken to /admin/store page and told that 'Default image support configured for Ubercart products'. However, when I click on products/view products it throws the following error:

Argument 1 passed to node_view() must be an instance of Node, bool given, called in /backdrop_root/web/modules/ubercart/uc_product/views/uc_product_handler_field_display_price.inc on line 30

I'm thus now in a loop where I cannot access the product settings to check or alter configuration.

This looks like a bug to me as it has appeared since latest release 1.x-3.13.0

Please help!
Rob
![Screenshot-status-report](https://user-images.githubusercontent.com/84332514/124453466-4d283d80-dd7f-11eb-8598-65580f18cd8e.png)

**Comment by robnacnamha** [comment]
I think I have resolved this issue! It appears to be associated with a content type I created for product with an image field. I have now deleted that content type and reinstalled ubercart and all looks OK so far. So I'm closing this issue.

**Comment by laryn** [comment]
Thanks for the report back @robnacnamha -- I hadn't had a chance to look at it yet but that explanation makes sense, I think!
