### ISSUE TITLE
Replace "Click here"

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/ubercart#279]
Several places in Ubercart label a link with the words "click here" or "click here to...". Nowadays most users won't be clicking (they'll be tapping). So we should update that verbiage, e.g., replace
```
l(t('Click here to view your file downloads.'), 'user/' . $account->uid . '/purchased-files'),
```
with
```
l(t('View your file downloads.'), 'user/' . $account->uid . '/purchased-files'),
```
or even just
```
l(t('File downloads.'), 'user/' . $account->uid . '/purchased-files'),
```
I personally tend to favor using verbs describing the action ("View your file downloads") as being clearer than nouns describing the destination ("File downloads").

**Comment by laryn** [comment]
I like `View your file downloads` as well.

**Comment by laryn** [comment]
Thanks @bugfolder!
