### ISSUE TITLE
Replace 'user_profile_item', 'user_profile_category' form items

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/ubercart#280]
There are several places in Ubercart that produce render arrays with
```
'#type' => 'user_profile_category',
```
(1 place, in `uc_roles`) and
```
'#type' => 'user_profile_item`,
```
(3 places, in `uc_file`, `uc_order`, and `uc_roles`). These types are no longer provided by Backdrop core, and so those items don't get rendered. In D7, for example, the user page provides links to a person's file downloads and orders, but these are missing from the user page in Backdrop.

Backdrop provides the `item` element, which is pretty close to what a `user_profile_item` used to be (it has `#title` and `#markup` elements), so that's a simple replacement. Replacing `user_profile_category` with `item` would also work, though that wouldn't provide much stylistic differentiation between the category title and roles.

**Comment by laryn** [comment]
Thanks @bugfolder!
