### ISSUE TITLE
Ubercart-Rules watchdog messages are all errors

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/ubercart#288]
I'll cross-post this until determined which module is doing this, but all watchdog messages from Ubercart Rules seem to be showing up as errors:

![image](https://user-images.githubusercontent.com/871421/140546476-9eda7e6f-33b2-4335-b62a-769b6f6564af.png)

**Comment by bugfolder** [comment]
I'm seeing this, so I'll start working on it.

**Comment by bugfolder** [comment]
The problem lies in the Rules module. Details and resolution are at https://github.com/backdrop-contrib/rules/issues/95.

**Comment by laryn** [comment]
Nice sleuthing!
