### ISSUE TITLE
delete config on uninstall

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-contrib/ubercart#3]
[issue filing for later fix]

**Comment by docwilmot** [comment]
Config should delete automatically on uninstall if a `hook_config_info()` is done.

**Comment by robertgarrigos** [comment]
thanks @docwilmot

**Comment by docwilmot** [comment]
This was due to missing return statement in `hook_config_info()` for all UC modules. Fixed in https://github.com/robertgarrigos/ubercart/pull/82 hopefully.

**Comment by robertgarrigos** [comment]
Thanks!
