### ISSUE TITLE
Notice: Trying to access array offset on value of type null in path_entity_update() with PHP 7.4 >

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/ubercart#311]
## Description of the bug

When visiting the cart/checkout page Ubercart is showing the following notice: Notice: `Trying to access array offset on value of type null in path_entity_update()`

## How to reproduce
IMPORTANT: you need to use PHP 7.4 or higher.

There are many ways to reproduce. The simplest:
- Add a product to the cart
- Proceed to Checkout
- Navigate away from that page (for example, go Home)
- Go back to `cart/checkout` (for example you may type the path in the browser)

The Notice is shown at that point. Another way to show this notice is to force an Ajax call that refreshes the page, for example, by clicking the checkbox for "My billing information is the same as my delivery information."

## Setup
- Fresh installation of BAckdrop  1.21.0-preview
- Fresh installation of Ubercart 1.x-3.x
- Fresh installation of Entity Plus 1.x and Entity UI 1.x
- Fresh installation of Rules 1.x-2.x
- IMPORTANT: This notice is only shown with PHP > 7.4 . It is not shown with 7.3 or lower

## Additional information
I've been able to reduce the issue to the following problem:
- PHP 7.4  gives the notice in line 494 of `path_entity_update()` for the assignment `$path['source'] =  $uri['path'];` when $uri is null. PHP 7.3 did not.
- The reason for $uri being null is that the entity class `UcOrderProduct` returns null for the method `uri()`
- This wouldn't be a problem (in fact entities at times do return null there) if the `uc_order_product` entity did not have a `path` property

The reason why the `uc_order_product` entity  has a `path` property is complex. `uc_order_product` entities are derived from `node` entities (one of the weaknesses of Ubercart is that it uses nodes as products, instead of using a completely independent entity). Since `node` entities do commonly use `path` properties (this is where the url alias information is stored upon loading or saving a node) this means that, in certain situations, `uc_order_product` entities "inherit" the `path` property from the node they are derived from. 

This confuses the hook implementation `path_entity_update()` into thinking that the `uc_order_product` entity does have a url alias (it doesn't) when Backdrop is saving or updating a `uc_order_product` to database. 

I think the easiest solution is to have the UcOrderProduct entity class return a value with the method `uri()`. According to my research this would cause no harm (but I need to test), and it would avoid this issue. The most likely candidate for a uri is simply the product node's uri.

**Comment by bugfolder** [comment]
I was seeing this error in some of the tests.

**Comment by argiepiano** [comment]
> I was seeing this error in some of the tests.

Yes, this was tripping several tests, since GHA uses 7.4 to run them.

**Comment by argiepiano** [comment]
PR #314
