### ISSUE TITLE
Fatal error in PHP 7.0 and 7.1 in buildContent() methods

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/ubercart#331]
As reported in Entity Plus https://github.com/backdrop-contrib/entity_plus/issues/117 , core's `EntityControllerInterface::buildContent()` now type-hints its first argument to `EntityInterface $entity`.  Since the interface  extension  `EntityPlusControllerInterface::buildContent()` and all the controllers that implement it DON'T, we have a method definition mismatch fatal error in PHP 7.0 and 7.1, and possibly others (7.3 and 7.4 seem to not care).

 Ubercart overrides `EntityPlusController::buildContent()` and as such, we need to type-hint the first argument to avoid this fatal error.

PR coming

**Comment by argiepiano** [comment]
PR #332 ready

**Comment by argiepiano** [comment]
Hey @laryn and @bugfolder. Just wanted to circle back about this PR. It's similar to one that was merged in Rules already, but hasn't been merged here. It's kind of an important one, as it will prevent fatal errors with PHP 7.1 and earlier.

**Comment by bugfolder** [comment]
Makes sense, thanks for the heads-up. Merge to follow.
