### ISSUE TITLE
Rules Update "uc_order_product" Tokens

### ISSUE THREAD

**Issue by and-e-h** [backdrop-contrib/ubercart#335]
Hi, just updated to Rules 1.x-2.3.1 and it required the installation of Entity Tokens. Now I'm receiving the warning below in Status Report....

Problems detected

The following token types are not defined but have tokens:

    $info['types']['uc_order_product']

**Comment by bugfolder** [comment]
@argiepiano, I see this, too. Any thoughts?

**Comment by argiepiano** [comment]
Yes. I see that as well. This is not harmful and should not cause any problems. Ignore it while I work on a fix. The error is produced by entity token

**Comment by argiepiano** [comment]
Please see the new release of Entity Tokens that fixes this issue  (version 1.x-2.0.1). Just released.

**Comment by argiepiano** [comment]
Thank you for reporting, @and-e-h! I will close this for now. Feel free to open another issue in Entity Tokens if this persists in your installation.

**Comment by bugfolder** [comment]
FWIW, I can confirm that the new version of Entity Tokens fixes the issue (needed some cache-clearing, though, to get the status report to update).

**Comment by and-e-h** [comment]
Many thanks for responding so quickly everyone! No further issues with Entity Tokens to report on my installation. :)
