### ISSUE TITLE
Ubercart wrongly overrides some Entity functions

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/ubercart#339]
From @docwilmot via https://github.com/backdrop-contrib/rules/issues/182:

> In a [recent core PR discussion](https://github.com/backdrop/backdrop/pull/4082#discussion_r884191749) we recognized that the `RulesConfigEntity()` class overrides the required `EntityInterface bundle()` method but returns nothing from that. Looking at the class closer, a number of its overriding methods also dont return anything. **Furthermore the classes `UcOrderProduct, UcOrder, and UcCartItem` do the same.** These should be fixed.

**Comment by bugfolder** [comment]
Since `UcOrderProduct` et al. extends `Entity`, and `Entity::bundle()` [returns the entity type by default](https://docs.backdropcms.org/api/backdrop/core%21modules%21entity%21entity.class.inc/function/Entity%3A%3Abundle/1), it might be sufficient to just not override `bundle()`.

**Comment by bugfolder** [comment]
I've removed the unnecessary overrides of `bundle()`, and have also cleaned up some of the other Entity functions. (Not sure that any of these were ever called anywhere, but it seems nice to have them correct if they ever do get used.)

**Comment by bugfolder** [comment]
Well, tests are failing, so might have gotten a little over-aggressive (or missed something). Will continue tinkering till tests pass again.

**Comment by argiepiano** [comment]
I think it has to do with the uri method of UCCartItem. This is one I added when I fixed the tests, because I think it was needed.  UcCartItem is a temporary entity that holds the product node while in the cart. The uri is not needed, since it's not viewed, but I seem to remember a definition was needed anyway. I may be wrong...

**Comment by argiepiano** [comment]
Yup. See #315

**Comment by bugfolder** [comment]
Yup, putting those back.

**Comment by argiepiano** [comment]
@bugfolder, these changes look fine. I added a couple of comments in the PR.

**Comment by argiepiano** [comment]
Thanks @bugfolder! This LGTM - ready to be committed!
