### ISSUE TITLE
Ubercart rules not added to the system

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-contrib/ubercart#34]
When you are in admin payments on ubercart (admin/store/settings/payment) you can see there is a payments list. Each with a "conditions" link and, maybe, also a "settings" one. No problem with the settings link, but conditions link results in a "not found" page. I tried with Drupal7 and had the same problem until I cleared the cache. However, clearing the cache in backdrop doesn't fix the problem.

To see it in action, enable all core ubercart modules plus payment and payment methode pack using main branch (1.x-1.x) of this repository.

**Comment by docwilmot** [comment]
@robertgarrigos the conditions are Rules forms. Rules itself is a bit alpha now. Maybe @Graham-72 could lend some insight there.

**Comment by robertgarrigos** [comment]
Thanks @docwilmot found the problem and reported in https://github.com/backdrop-contrib/rules/issues/7. It is related to the problem of creating new rules (https://github.com/backdrop-contrib/rules/issues/3)

**Comment by docwilmot** [comment]
Fixed with https://github.com/backdrop-contrib/rules/issues/21

**Comment by robertgarrigos** [comment]
Yes! thanks.
