### ISSUE TITLE
Error rules (>= 2.2.0) does not exist in your Backdrop installation.

### ISSUE THREAD

**Issue by alanmels** [backdrop-contrib/ubercart#342]
[Line 8 ](https://github.com/backdrop-contrib/ubercart/blob/882c96917166c68c37648625c110490d30521b86/ubercart.info#L8) of ubercart.info has:

```
dependencies[] = rules (>= 2.2.0)
```

However, looking at https://github.com/backdrop-contrib/rules/releases I see there is no such branch as 2.2.x at all. The actively maintained version is [1.x-2.3.2](https://github.com/backdrop-contrib/rules/releases/tag/1.x-2.3.2) So this line has to updated to let install go through.

**Comment by argiepiano** [comment]
I'm a bit confused. That line says that you must have a Rules version equal or higher than 2.2.0. The current version is 2.3.2, which is higher. Are you getting an error? Can you check the Rules module in your modules folder to see what version you have?

**Comment by alanmels** [comment]
This is what it was giving on CLI:

```
drush en ubercart
The following projects will be enabled: rules (>= 1.x-2.2.x), system (>= 1.21.0), ubercart.
    Do you want to enable the projects? (y/n): y

	Error rules (>= 1.x-2.2.x) does not exist in your Backdrop installation.
	Try downloading rules (>= 1.x-2.2.x) first with the command: drush dl rules (>= 1.x-2.2.x)
```

Maybe it was comparing with the long version number `[1.x-2.3.2](https://github.com/backdrop-contrib/rules/releases/tag/1.x-2.3.2)` which is not the same as `2.3.2`.

**Comment by argiepiano** [comment]
Have you checked which version of Rules you have in your modules folder? Open rules.info to check. If you don't see version there it means you may have the 1.x-2.x dev version.

You cannot use the dev version - Backdrop's core check will not consider 1.x-2.x higher than 2.2.0.

BTW Backdrop automatically removes the "1.x" part when doing the comparison.

I've never seen this issue when working with a released version, so my suspicion is that you are either working with a dev version, or working with an old version of Rules. 

Please provide this information  (exact version of Rules you have by opening rules.info) to see if I can get to the bottom of this. BTW, Ubercart/Rules is not the only module that uses version requirements, and it's never been reported to not work. 

Additionally, check to see if the error only happens with drush - try using the Installer UI.

Thanks

**Comment by alanmels** [comment]
Thanks for the details, it was dev version of Rules.
