### ISSUE TITLE
Support using mail system classes other than DefaultMailSystem

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/ubercart#345]
In Backdrop, the default mail system is class [DefaultMailSystem](https://docs.backdropcms.org/api/backdrop/core%21modules%21system%21system.mail.inc/class/DefaultMailSystem/1), but it is possible to override this by defining a new class and storing its name in `system.mail` config as `default-system`. An example where this is done is the [SMTP module](https://backdropcms.org/project/smtp), which creates `SmtpMailSystem` as the new system default mail class.

Ubercart defines its own mail system class, `UbercartMailSystem`, which is used for all emails, such as order emails and the like. However, the class lineage is hard-coded as

```
class UbercartMailSystem extends DefaultMailSystem {
...
```

So, even if the user has implemented another mail system (for example, the aforementioned SMTP mailer), Ubercart will attempt to use the DefaultMailSystem at its heart, which is likely to fail (if the host system did not support outgoing mail, driving the user to use SMTP).

It would be nice, then, if `UbercartMailSystem` extended whatever mail class was set in `system.mail`.

PR to follow.

**Comment by argiepiano** [comment]
I think this is a nice idea. However, notice that there are only two methods in `MailSystemInterface`: `MailSystemInterface::format()` and `MailSystemInterface::mail()` used for delivery. `UbercartMailSystem` only overrides `format()`, meaning that, yes, if you use the basic Backdrop mail system selection (that is, the config file), you can't opt to use a different `mail()` method other than the one provided by `DefaultMailSystem`.

However, if you install `mailsystem`, you have the option of selecting a method from one class for formatting, and a different one for delivery, which basically takes care of the use case you mention above. You are even able to specify which class to use for formatting and delivery based on the module itself that implements hook_mail! 

That said, I think it's pretty handy to be able to do this for Ubercart without the need to install mailsystem. 

I haven't tested your PR. The approach is something I haven't seen before in Drupal/Backdrop contexts, though. Is that a common way to do this?

**Comment by bugfolder** [comment]
> Is that a common way to do this?

Dunno. I'd not seen it before, but I found the basic idea on StackExchange (along with the expected warnings about using `eval()`). But it works nicely on the site I'm developing that uses SMTP for mailing.

**Comment by argiepiano** [comment]
> I found the basic idea on StackExchange (along with the expected warnings about using eval()).

I see. TBH the `eval` makes me a bit nervous. Also the fact that this code is not part of a function.  I'm wondering if there is a better way to do this. 

Something that comes to mind (which is what mailsystem does) is to create an "intermediary" Ubercart class that takes care of calling `format` or `mail` from another class (this is called a [delegate pattern](https://gist.github.com/fimak/89d01b24f7f7a835153e)), and it would be fairly simple to implement in this case. The methods `format` and `mail` of this delegate class would invoke the specific methods from a given class set in a config file. 

As a user, you would then have the ability to pick any `mail` or `format` method from any given system.

What do you think?

**Comment by argiepiano** [comment]
In a nutshell, this is what the `format` method of the delegate Ubercart mail class would look like:

```php
  public function format(array $message) {
    $module = $message['module'];
    $key = $message['key'];
    $mailsystem = _ubercart_delegate_get_mailsystem($module, $key, 'format');
    return $mailsystem->format($message);
  } 
```

and the _ubercart_delegate_get_mailsystem would simply instantiate the class from a config file and return the object

**Comment by argiepiano** [comment]
So this is how the complete class would look like, assuming that you want to keep `UbercartMailSystem::format` intact (which is what your PR does) and use the `mail` method from whatever class is defined in `system.mail`:

```php
class UbercartMailSystem implements MailSystemInterface {

  /**
   * Concatenates and wraps the e-mail body for plain-text mails.
   *
   * @param $message
   *   A message array, as described in hook_mail_alter().
   *
   * @return
   *   The formatted $message.
   */
  public function format(array $message) {
    $message['body'] = implode("\n\n", $message['body']);
    return $message;
  }

  /**
   * Implements MailSystemInterface::mail().
   *
   * Retrieve the configured class responsible for delivering a message 
   * defined by system.mail. Forwards the call to that class.
   */
   public function mail(array $message) {
    $mailsystem_name = config_get('system.mail', 'default-system');
    $mailsystem = new $mailsystem_name()
    return $mailsystem->mail($message);
  }
}
```

I find this better than using `eval`, given that there are only two possible methods for these mail classes.

**Comment by argiepiano** [comment]
[Edited some typos and errors above]

**Comment by argiepiano** [comment]
[and some more editing 😄 ]

**Comment by argiepiano** [comment]
And one more thing. If you end up using this idea, you'll need to code something to avoid circular references. That is, if someone sets `system.mail` to user UbercartMailSystem as the default, you would need to check for this and use `DefaultMailSystem`.

BTW, this problem (circular reference) also exists in your PR at this point.

**Comment by bugfolder** [comment]
> I find this better than using `eval`, given that there are only two possible methods for these mail classes.

Agreed, thanks for the thorough discussion. Updates to follow shortly.
