### ISSUE TITLE
Non-shippable products result in "Notice: Trying to access array offset on value of type null"

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/ubercart#348]
Specifically, when going through the checkout after purchasing a non-shippable product (a file download), I get a watchdog notice:

Notice: Trying to access array offset on value of type null in `uc_quote_uc_order()` (line 322...)

This happens in this code:

```
    case 'load':
      $quote = db_query("SELECT method, accessorials, rate FROM {uc_order_quotes} WHERE order_id = :id", array(':id' => $order->order_id))->fetchAssoc();
      $order->quote = $quote;
      $order->quote['accessorials'] = strval($quote['accessorials']);
      break;
```

If there's no shipping quote in the db, then `$quote` is NULL, and the warning happens. The fix is simple:

```
    case 'load':
      $quote = db_query("SELECT method, accessorials, rate FROM {uc_order_quotes} WHERE order_id = :id", array(':id' => $order->order_id))->fetchAssoc();
      if (!empty($quote)) {
        $order->quote = $quote;
        $order->quote['accessorials'] = strval($quote['accessorials']);
      }
      break;
```

PR to follow.

**Comment by argiepiano** [comment]
Thanks @bugfolder. Please notice a [slightly different approach for Drupal](https://www.drupal.org/project/ubercart/issues/3218992) (which has not been merged). I haven't had the time to compare and test, but I see there that they avoid the notice by specifically targeting the $quote variable.   This seems rather contrived, but...

I'm not sure if completely skipping setting $order->quote may create issues in other places, like in the checkout panes? Perhaps it's still a good idea to set  `quote` even if it's null or empty?

**Comment by bugfolder** [comment]
The Drupal patch is:

```
     case 'load':
       $quote = db_query("SELECT method, accessorials, rate FROM {uc_order_quotes} WHERE order_id = :id", array(':id' => $order->order_id))->fetchAssoc();
       $order->quote = $quote;
-      $order->quote['accessorials'] = strval($quote['accessorials']);
+      $order->quote['accessorials'] = (isset($quote['accessorials']) ? strval($quote['accessorials']) : '');
       break;
```

If there's no result, [fetchAssoc()](https://docs.backdropcms.org/api/backdrop/core%21includes%21database%21database.inc/function/DatabaseStatementBase%3A%3AfetchAssoc/1) should return FALSE, which means that `$order->quote` will be FALSE.

So then the attempt to set the value of `$order->quote['accessorials']` should result in a PHP error.

> I'm not sure if completely skipping setting $order->quote may create issues in other places, like in the checkout panes? Perhaps it's still a good idea to set quote even if it's null or empty?

I haven't tried this, but the change here is in use on a live site (which is how I discovered the issue) and I've not seen any other warnings yet.

**Comment by bugfolder** [comment]
I think the Drupal patch was addressing a different case: one where the quote existed, but its accessorials were missing. This issue is the case where there's no quote at all. I've updated the PR to include the Drupal patch case as well.

**Comment by argiepiano** [comment]
I don't think the added check for accessorials to be set is necessary. The Drupal version had it there to avoid the notice (since the variable $quote was false, PHP 8.1 throws a notice when checking a key of a non-array). So, your original code should be sufficient (and is probably better than checking accessorials). If a quote exists in the DB, then `accessorials` will always be set, as it's marked as `not null` in the table definition. 

I've been trying to test this to see if an unset order object property `quote` would cause any issues. I'm running into problems in my testing - first, I don't have 8.1 installed. Second I can't get Ubercart Quote and Shipping to work. I've enabled Shipping, Shipping Quotes, Flat Rate, U.S. Postal Service, and set an address for the store. Also selected a shipping method for a shippable product. I'm still not seeing the Shipping option at checkout. Any hint on what I'm missing?    

EDIT: OK, I think I need to input a USPS user id. Is there a way to test shipping quote without that?

**Comment by bugfolder** [comment]
> I don't think the added check for accessorials to be set is necessary. 

You're right; reverted.

**Comment by bugfolder** [comment]
> I've been trying to test this to see if an unset order object property quote would cause any issues. 

Can you use `uc_weightquote` to get a shipping quote without needing a USPS account?

The only shipping method I've used is a heavily customized version of `uc_usps`, so haven't played around with any of the others.

**Comment by argiepiano** [comment]
I've been only able to test with flat rate quote, which effectively removes the choices of different quotes (which is what I wanted to test).

At first sight your patch should not create problems, but I'd like to try to test the following situations to be sure:
- Mix of shippable and non-shippable prods in the cart
- Choices of different quotes (flat, usps, etc). 

I'll need to come back to this. I'm still out of town. I'll try to get to this over the weekend. If you could test some of the above too, that'd be great.

Thanks for the work on this!

**Comment by argiepiano** [comment]
I've been able to test the patch with two different quote methods  and with and without shippable products. No problems. RTBC on my end!
