### ISSUE TITLE
Module name capitalization

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/ubercart#352]
Per https://docs.backdropcms.org/creating-modules, module names should be capitalized:

> Since module names are proper names, they should be capitalized as such (capitalize all words in the name - including any "helper" words, such as "the", "of", "for" etc.). So it should for example be "Cool Things For Sites"; not "cool things for sites", nor "Cool things for sites", nor "Cool Things for Sites").

PR to follow.

**Comment by argiepiano** [comment]
Thanks! Left a small comment in PR.
