### ISSUE TITLE
[D7] [PHP 8.0] Deprecated function: Required parameter $qty follows optional parameter $data in uc_product_uc_update_cart_item()

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/ubercart#354]
This is the [counterpart D7 issue](https://www.drupal.org/project/ubercart/issues/3267028). 

`uc_product_uc_update_cart_item()` has $data as optional, and is followed by $qty which is not. This throws a `Deprecated function` notice in PHP 8.

**Comment by argiepiano** [comment]
There is one more instance of this: `uc_product_kit_uc_update_cart_item()`

**Comment by argiepiano** [comment]
PR #355 ready for review

**Comment by bugfolder** [comment]
LGTM.

Unless anyone objects, I'll merge this and other PRs and do a new release tomorrow (Aug 1).
