### ISSUE TITLE
UcAddress and config: goes in as object, comes out as array

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/ubercart#360]
Ubercart uses the `UcAddress` object to represent addresses, but in some places (e.g., forms) it needs to convert those objects to arrays. So both are in use, and we need to take care in any given bit of code to make sure we're not mixing objects and arrays.

This issue comes up because of a quirk in Backdrop's Configuration Management. In most cases, calls to `variable_get()` can be replaced with corresponding calls to `config_get()` or `state_get()`. However, while `variable_set()`/`variable_get()` can store/retrieve objects as objects, `config_set()` stores objects as arrays, so that `config_get()` will retrieve an array, even if it was an object originally. `state_set()`/`state_get()` handles objects, like `variable_set()`/`variable_get()`.

This behavior can be seen by running this code snippet:

```
$foo = new StdClass();
$foo->field = "value";
config_set('my_test.settings', 'foo', $foo);
dpm($foo,'$foo');
$bar = config_get('my_test.settings', 'foo');
dpm($bar,'$bar');

state_set('my_test_foo', $foo);
dpm($foo,'$foo');
$bar = state_get('my_test_foo');
dpm($bar,'$bar');
```

There are several places in Ubercart where we retrieve `UcAddress`s from config and they come in as arrays, but we want objects.

The `UcAddress` class has a magic static method, `__set_state($data)`, which takes in an array and returns the corresponding `UcAddress` object. Calls to `config_get(...)` that are returning an address should be wrapped in this function if an object is what is desired.

It's a static method, so there is no need to create an empty object prior to calling it.

With that all said, a PR follows that fixes some inconsistencies in object/array for addresses retrieved from config.

**Comment by argiepiano** [comment]
Looks good to me!
