### ISSUE TITLE
Request: Add link to Backdrop UC wiki to the D7 docs for UC

### ISSUE THREAD

**Issue by albanycomputers** [backdrop-contrib/ubercart#367]
Add a link in the wiki or readme etc... to the D7 docs for UC.

https://www.drupal.org/docs/7/modules/ubercart

We could also recreate the docs if we get permission.

**Comment by bugfolder** [comment]
Good suggestion! Thanks, @albanycomputers. Merged.

**Comment by albanycomputers** [comment]
Update the link to reflect the Backdrop initiative to convert the docs from D7 to Backdrop...

www.ubercart.dev
