### ISSUE TITLE
Cross-port of Issue #3270003 by poker10: UbercartCreditCardTestCase::testCheckout()

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/ubercart#369]
Cross-port of https://git.drupalcode.org/project/ubercart/-/commit/957650ee2becf56c985dd0aab1534d18666fbd96.

This commit fixed a test that used a hard-coded expiration date for the credit card of 2022. Previous fix to Backdrop Ubercart had set this value to 2032, but the D7 UC commit sets it to always be 5 years in the future, so we should match this for consistency. (One hopes that UC is still in use in 10 years!)

**Comment by argiepiano** [comment]
LGTM!
