### ISSUE TITLE
Reports URL incorrect on List Modules page

### ISSUE THREAD

**Issue by albanycomputers** [backdrop-contrib/ubercart#376]
When the modules are listed under "Functionality > List Modules" the **Ubercart-Core** - **Reports** "Configure" link is incorrect.

![image](https://user-images.githubusercontent.com/1705388/198887258-3d10410a-5569-4c7b-a375-81dc7b248317.png)

The existing link is...  /admin/store/settings/store

this should be... /admin/store/settings/reports

Suggested change to file: ubercart/uc_reports/uc_reports.info

Change line 8 from: -
configure = admin/store/settings/store

to: -
configure = admin/store/settings/reports

**Comment by bugfolder** [comment]
Good catch, fixed and merged. Thanks, @albanycomputers!

**Comment by albanycomputers** [comment]
I'm working through the documentation I sent a link to on the D7 site... and updating the docs to Backdrop... So I may find more :)

I'll let you know when it's complete so you can link to the new docs that are more relevant to Backdrop/Ubercart.
