### ISSUE TITLE
State of Capitalize address on order screens not being saved.

### ISSUE THREAD

**Issue by albanycomputers** [backdrop-contrib/ubercart#378]
On **store>configure>store (/admin/store/settings/store)** menu option...
On the **Display settings tab** 

The state of the option **Capitalize address on order screens** is not being saved and reverts back to being ticked.

![image](https://user-images.githubusercontent.com/1705388/199311436-e093e90e-040b-4a13-be92-5dd8038a80ae.png)

**Comment by bugfolder** [comment]
Thanks for flagging this. Yes, it's a bug, due to a missing `#config` property in `uc_order_form_uc_store_settings_form_alter()`. PR to come.

**Comment by bugfolder** [comment]
Thanks, @albanycomputers! Fix is merged into 1.x-3.x.
