### ISSUE TITLE
Allow UbercartCartCheckoutTestCase::setUp() to pass through the $modules array received as parameters 

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/ubercart#380]
Currently, `UbercartCartCheckoutTestCase::setUp()` takes the array `$modules` as the first parameter, but this parameter is completely ignored in the next line:

`$modules = array('uc_payment', 'uc_payment_pack', 'uc_roles');`

Instead, the new modules array should be merged with the passed `$modules` parameter. 

The module `uc_addresses` extends this test to do its own testing. Because of the current bug, this extended class cannot set up its own tests correctly.

**Comment by argiepiano** [comment]
PR #381

**Comment by bugfolder** [comment]
Thanks, @argiepiano!
