### ISSUE TITLE
uc_reports: add more options to custom product report

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/ubercart#384]
The custom product report (admin/store/reports/products/custom) lets you customize the report with start and end date and order statuses:

![before](https://user-images.githubusercontent.com/29214084/201440274-eab071d1-cd1f-4974-82e3-a69d5874b3ec.jpg)

But it would be nice to add additional criteria: product types, whether or not a product has been sold within the specified period, and whether or not it is stock-tracked. Like this:

![after](https://user-images.githubusercontent.com/29214084/201440335-13d2e28c-0939-4003-8aaf-39ee01025ccb.jpg)

It's straightforward to add these settings to the customization parameters. PR to follow.

**Comment by argiepiano** [comment]
This looks good to me. I left a couple of minor comments in the PR.

I don't use uc_reports, so I don't have a way to test thoroughly, but my very light testing seems to work fine.

**Comment by bugfolder** [comment]
Thanks for review and comments, PR updated! (We'd been using this mod "in the wild" for several years; the store manager finds it quite helpful.)
