### ISSUE TITLE
uc_reports produces `file_get_contents(misc/tableheader.js): failed to open stream` warning

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/ubercart#386]
Line 786 of `uc_reports.admin.inc` (in function `theme_uc_reports_product_table()` has the wrong path to `tableheader.js`. The correct path is `core/misc/tableheader.js`.

This is only seen after clearing the cache and visiting `admin/store/reports/products`

EDIT: The line number is different in the dev version.

**Comment by argiepiano** [comment]
PR #387

**Comment by bugfolder** [comment]
So it is. Nice catch, thanks!
