### ISSUE TITLE
The function uc_product_enable() (uc_product.install:233) called deprecated function node_types_rebuild().

### ISSUE THREAD

**Issue by alanmels** [backdrop-contrib/ubercart#396]
Installing the module on a fresh Backdrop (PHP 7.4.29) site gives:

```
The function uc_product_enable() (uc_product.install:233) called deprecated function node_types_rebuild(). It will be removed in the next major release of Backdrop.
```

**Comment by bugfolder** [comment]
Yes, that call looks entirely superfluous. `node_types_rebuild()` docs say:

> Backdrop no longer needs to "rebuild" its node types, which previously were synced between the code and database in Drupal 7.

And the call in `uc_product_enable()` to `node_types_rebuild()` is immediately followed by `$types = node_type_get_types();`, which, via `_node_types_build()`, does a fresh read-in of the types from caches or (config) disk.

**Comment by bugfolder** [comment]
I see that `node_types_rebuild()` gets called in 6 different places in Ubercart. We should check, but they're probably all superfluous.

**Comment by bugfolder** [comment]
Test failed, so further work needed.

**Comment by bugfolder** [comment]
Tests fixed. Node types don't need explicit rebuilding, but we do need to clear the node type cache after changes.

**Comment by argiepiano** [comment]
Left a question in the PR.

**Comment by bugfolder** [comment]
`node_type_cache_reset()` added at the questioned location, PR updated. Currently failing tests are unrelated to this PR.

**Comment by argiepiano** [comment]
This looks fine. I actually did some trace-testing with uc_product_enable(), and it looks like `node_type_cache_reset()` is not needed after all. At some point during the installation of ubercart, the node type static cache is built to include the `product` type. But it doesn't do any harm, either.

RTBC
