### ISSUE TITLE
Restore Ubercart footer functionality previously provided by uc_store_page_alter().

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/ubercart#397]
EDIT: original title was "uc_store_page_alter() doesn't do anything".

In `uc_store.module`, the function `uc_store_page_alter()` implements `hook_page_alter()`, but that is not a Backdrop hook.

Also `uc_cybersource.module` implements this hook in `uc_cybersource_page_alter()`.

**Comment by argiepiano** [comment]
I see that `uc_store_page_alter()` is used to display the store footer configured in `admin/store/settings/store`. 

That footer display has some preset configurations available in the path above. I think the best way to handle the fact that the hook is not available is to define an ubercart footer block, and have those configurations be part of the new block options.

**Comment by argiepiano** [comment]
As for `uc_cybersource_page_alter()` it looks like it's used to add some hidden fields to the `uc_cart_checkout_review_form` form. I think the same can be accomplished with hook_form_alter instead.

**Comment by bugfolder** [comment]
> I think the best way to handle the fact that the hook is not available is to define an ubercart footer block, and have those configurations be part of the new block options.

Yeah, was thinking something like that, too so as not to lose the functionality.

**Comment by bugfolder** [comment]
Moved `uc_cybersource_page_alter()` to its own issue.

**Comment by bugfolder** [comment]
I've created a PR that adds the footer block and a new layout visibility condition, "Ubercart page" (`UbercartLayoutAccess`), that can allow the block to be displayed only on Ubercart pages (replicating the logic that was in `uc_store_page_alter()`). A nice thing about using Backdrop's layout visibility system is that this condition could be used for any block, so, for example, to display a "Daily Special" block only on Ubercart pages.

@robertgarrigos, @laryn, @argiepiano, three questions come to mind:

- I left the options at `admin/store/settings/store` for the moment (for consistency with D7 and current Backdrop), rather than making them block options as suggested above. My thinking was that store configurators are more likely to discover the settings here. OK?
- Should the "Ubercart page" layout condition allow the user to add optional additional paths? For example, the store admin might have created some Views that display the catalog and/or products in different ways that should also get the footer. (Although they could just make sure the path starts with `catalog/`, which would be picked up by the existing logic.)
- Currently this block is made available, but it isn't placed anywhere by default. If we want to replicate the D7 behavior upon upgrade, should we try to place this block in the footer region of all layouts during upgrade from D7?

**Comment by argiepiano** [comment]
Hi @bugfolder - thanks for this, it looks great! I left a comment in the PR (you used `==` instead of `=` to assign a value to a variable).

Also, after placing the block and setting the visibility condition,  if I go to `admin/store/settings/store` and click "Display settings" and then choose "Do not display a message in the footer" the footer is still shown, plus I get `Notice: Undefined variable: path in uc_store_block_view() (line 683...` when I visit a product page ($path is never defined)

**Comment by argiepiano** [comment]
>Should the "Ubercart page" layout condition allow the user to add optional additional paths? For example, the store admin might have created some Views that display the catalog and/or products in different ways that should also get the footer. (Although they could just make sure the path starts with catalog/, which would be picked up by the existing logic.)

Admins can already do that - sort of. There is a "URL path" visibility condition that allows you to list paths where the block will (or will not) be shown. The only issue here is that you can't have both visibility conditions ("URL path" AND "Ubercart page") applied to the same block, as these two conditions are applied as "and" rather as "or". (Don't you wish we had the ability to specify "and" or "or" groups to Layout Visibility conditions, like in Rules or Views?)
  
> Currently this block is made available, but it isn't placed anywhere by default. If we want to replicate the D7 behavior upon upgrade, should we try to place this block in the footer region of all layouts during upgrade from D7?

I think that may be a good idea. Are you thinking of doing an upgrade hook for this?

**Comment by bugfolder** [comment]
>> Should the "Ubercart page" layout condition allow the user to add optional additional paths?

> Admins can already do that - sort of. There is a "URL path" visibility condition that allows you to list paths where the block will (or will not) be shown. The only issue here is that you can't have both visibility conditions ("URL path" AND "Ubercart page") applied to the same block, as these two conditions are applied as "and" rather as "or". (Don't you wish we had the ability to specify "and" or "or" groups to Layout Visibility conditions, like in Rules or Views?)

Exactly, and that was my thinking. (And yes, an "or" visibility condition would be a great add! I feel a new core issue coming on...) So what I was mulling was adding the equivalent of "URL path" visibility field inside this Ubercart visibility condition that would give the user an effective "or" condition: if the URL is any of [the current condition] `cart/*`, `catalog/*`,` admin/store/*`, `node/*` if node type is an Ubercart product, or [to be added] any of the paths in the additional field.

Adding the extra rigamarole just to get the Ubercart footer on those additional pages doesn't seem like a particularly strong use case, because there is a workaround: the admin could add a second copy of the footer block with its own, separate "URL path" visibility condition. But as a convenience for site architects to be able to put other Ubercart-specific blocks on Ubercart-only pages, perhaps it's warranted.

>>If we want to replicate the D7 behavior upon upgrade, should we try to place this block in the footer region of all layouts during upgrade from D7?

>I think that may be a good idea. Are you thinking of doing an upgrade hook for this?

Yes. 

I'm also thinking of removing the "none" setting from the store settings, since that would just create an empty footer block (and that might be confusing for someone trying to place that block on the layout page, but not seeing anything show up on a test page and not realizing that "none" was selected in a store setting that is buried in a vertical tab group). With a separate footer block, "don't show it" is achieved by either not placing the block or placing but disabling it.

Thus, for upgraders, we'd do this in the upgrade hook:

* If a footer message was selected in D7, try to place the footer block in the footer region of all layouts with the Ubercart page visibility condition.
* If the footer message was set to "none", change the setting to the default (first) message (so there is a valid setting), but don't try to place the block.

And for new installations, in `hook_enable()`, set the message to the first (default) value and try to place the footer block in the footer region of all layouts with the Ubercart page visibility condition.

**Comment by argiepiano** [comment]
@bugfolder thanks for providing fixes to my comments and for the response above. 

Here's an additional thought. Having the configuration of this message under Store > Configuration > Store > Display settings seems a bit confusing now that this is a block. Would it make more sense to have the options under "Footer message for store pages" be part of the new block configuration? So, when you add the block, you can decide where it will be shown (through the new visibility condition) AND also what kind of message it will display (the difference between this and a regular Custom Block is the ability to randomly select a message to be displayed). 

I realize that this change may be confusing for someone upgrading from D7, but perhaps we can have a message under "Footer message for store pages" in the ubercart configuration UI saying something like "These settings are now part of the Ubercart footer block. Please check ..." or something like that.

**Comment by bugfolder** [comment]
> I realize that this change may be confusing for someone upgrading from D7, but perhaps we can have a message under "Footer message for store pages" in the ubercart configuration UI saying something like "These settings are now part of the Ubercart footer block. Please check ..." or something like that.

Yeah, having that setting hidden elsewhere in a block was bothering me, but adding a message to the Store settings would address that.

**Comment by bugfolder** [comment]
Created a new block class `UcBlockFooter` that contains the footer message settings and then cleaned up the Store admin page a wee bit.

Still to do are the update and <strike>enable</strike> install hook implementations for upgrades and enablement.

**Comment by bugfolder** [comment]
Oops, tests passed, but manual tinkering resulting in a crash. More work needed on the basic implementation.

**Comment by bugfolder** [comment]
OK, further changes made, now ready for (re)review. To summarize:

- On the store configuration page at `admin/store/settings/store`, the former footer radio buttons are removed, and a new "Footer" vertical tab is added with some help text and link to the layout administration.
- There is a new available block, "Ubercart store footer," whose settings allow you to set the footer message.
- There is a new block visibility condition, "Ubercart page," which allows you to restrict the block to appear on the Ubercart-governed pages that `uc_store_page_alter()` previously put the footer on. In addition, you can define additional paths to be included in this visibility condition if desired.
- Upon initial enabling of Ubercart, the block and visibility condition will be added to the default layout, default admin layout, and any layout with the path `node/%` (which could be a product page), using the default footer message (randomly selected).
- For updates (from previous versions of Backdrop Ubercart or from D7 Ubercart), the block and visibility conditions will be added as above, unless the footer message had been previously set to `'none'`.

Although this seems like a lot of work for something that many users would have turned off anyhow, and no one seems to have missed it up to now, I think the visibility condition will turn out to be useful in general for adding blocks (e.g., "Daily special") to Ubercart pages.

**Comment by argiepiano** [comment]
Hi @bugfolder, and thanks for your continued work.

I'm testing this:
1. I added the Ubercart footer in the Default Layout's footer region
2. I added the new Visibility condition and configured "Allow access on all Ubercart pages" (first problem: the textarea for "Additional paths" is currently required, so I can't leave that empty. So, I entered "node/1") 👎🏽 
3. I visited an Ubercart product page and the footer shows up 👍🏽 
4. I visited a regular Page (non-product, not node/1), and the footer still shows 👎🏽 

I'm working with a Vanilla install, no other modules (other than dependencies) and a downloaded 1.x-3.x dev version of Ubercart, which I patched manually with the 414.diff patch

**Comment by argiepiano** [comment]
BTW, in my testing, Ubercart was already enabled (so I did not test the default placement of the block). I think many users will have this same environment when they upgrade Ubercart to the next version, containing these features.

**Comment by bugfolder** [comment]
Grrr. Missing `break` in `switch` (that's never happened to anyone). And blindly copying the form element from the URL path access condition. Both fixed, I think; could you test again?

**Comment by argiepiano** [comment]
Reviewed and tested - works great! I left a question in the PR

**Comment by argiepiano** [comment]
Thanks! RTBC!

**Comment by bugfolder** [comment]
Great! Maybe we can do another minor release at the same time as 1.24. (And I'll now do some testing of https://github.com/backdrop-contrib/ubercart/issues/415, which looks intriguing.)
