### ISSUE TITLE
Anonymous (guest) checkout

### ISSUE THREAD

**Issue by djzwerg** [backdrop-contrib/ubercart#399]
Hi,
is it possible to provide a way for complete anonymous checkout? For now every anonymous customer gets an account created after finishing the checkout progress. I think this is not really the way 'anonymous' means.

**Comment by bugfolder** [comment]
This behavior—creating an account for anonymous users—is pretty deeply embedded in how Ubercart keeps track of orders. There's some discussion of this and rationale in [this Drupal issue](https://www.drupal.org/project/ubercart/issues/2071851). (Longwave is one of the main D7 maintainers.)

So, going to close this one, sorry.
