### ISSUE TITLE
The function theme_uc_store_address_fields_form() (uc_store.admin.inc:205) called deprecated function element_sort().

### ISSUE THREAD

**Issue by alanmels** [backdrop-contrib/ubercart#401]
Just go to https://yoursite.ddev.site/admin/store/settings/countries/fields and it will give this deprecation notice:

`The function  theme_uc_store_address_fields_form() (uc_store.admin.inc:205) called  deprecated function element_sort(). It will be removed in the next major  release of Backdrop.
`
The fix is easy as per https://docs.backdropcms.org/change-records/generic-sorting-function-to-replace-implementations-of-uasort, the line:
`
uasort($form['fields'], 'element_sort');`

should be replaced with

`backdrop_sort($form['fields'], array('#weight'));`

**Comment by bugfolder** [comment]
Tested, it works. Merged. Thanks, @alanmels!
