### ISSUE TITLE
How to get $billing_company value in invoice template?

### ISSUE THREAD

**Issue by djzwerg** [backdrop-contrib/ubercart#404]
Hi. Is there any way to get the `billing_company` value itself in the invoice template? I tried these:

```
$billing_company
$billing_company_op;
$order_billing_company_op;
$order->{$type . '_company'}
$order_billing_company; 
$order_address_company;
$address_company;
$order_company
```

but none of these works 😢

**Comment by bugfolder** [comment]
In `uc-order--customer.tpl.php` use `$order->billing_company`.

To examine what variables are available, install the Devel module, turn on permissions for the administrator, and then add this line to the beginning of `template_preprocess_uc_order(&$variables)`:

```
dpm($variables,'$variables');
```

All of those variables get exposed to the template.

HTH

(Of course, don't forget to remove the `dpm()` call when you're done!)

**Comment by djzwerg** [comment]
Thanks @bugfolder this works!
