### ISSUE TITLE
Add www.ubercart.dev to the README file

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/ubercart#405]
We currently recommend the [Drupal Ubercart documentation](https://www.drupal.org/docs/7/modules/ubercart) in the README file. Recently, Steve Moorhouse (DrAlbany) started a Backdrop-specific Ubercart site, [www.ubercart.dev](https://www.ubercart.dev). Perhaps we should add a reference to this to the README file's Documentation section.

**Comment by albanycomputers** [comment]
Sounds good to me.
