### ISSUE TITLE
Deprecated function: Automatic conversion of false to array in uc_cart_block_view()

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/ubercart#407]
Cross-port of https://www.drupal.org/project/ubercart/issues/3324072 (recently fixed in D7 Ubercart).

There is a PHP 8 deprecation message in `uc_cart_block_view()`. (Quoting the D7 issue):

Deprecated function: Automatic conversion of false to array is deprecated in uc_cart_block_view() (line 338 in  /.../ubercart/uc_cart/uc_cart.module).

**Comment by argiepiano** [comment]
LGTM!
