### ISSUE TITLE
Streamline use of `uc_cart_item` and `uc_order_product` entities in an order entity

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/ubercart#415]
This not a bug report, but rather a proposal for some code improvement on how `$order->products` are first set, and what kind of classes that array of products holds.

Background
----
When Ubercart was ported to Backdrop, the developers added named classes for all Ubercart custom entities:
- `uc_cart_item` (entity class `UcCartItem`). This entity type is a temporary holding entity for products that are in the shopping cart. They are saved in table `uc_cart_products`.
- `uc_order` (entity class `UcOrder`)
- `uc_order_product` (entity class `UcOrderProduct`). This entity type is used to hold products that are already in an order. The are saved in table `uc_order_products`.

Previously, D7 used the generic class `stdClass` to hold all these entities. Using named classes made a lot of sense given that Backdrop has a slimmed down version of Entity API in core. 

This change created some issues when Backdrop added `Entity::view()` in core (https://github.com/backdrop/backdrop-issues/issues/1739), which, in combination with Entity Plus' `entity_plus_view()`, created unintended effects when Ubercart builds the view of products during the checkout process - see #309.

The issue we found in #309 was that `uc_order_product_view_multiple()` was being passed an array of `UcCartItem` entities when the customer first moved from the cart page to the checkout page. This array was then passed to `entity_plus_view()`, BUT using a first parameter `'uc_order_product'`, which indicates that the entity types being passed should have been an array of `UcOrderProduct`.

The patch that I provided there converted those `UcCartItem` array of products into an equivalent array of `UcOrderProduct` before passing them to `entity_plus_view()`. This works fine, but it's rather hacky, and it doesn't address the cause of the issue.

Proposed streamlining
----

I'm proposing to streamline the code so that `UcOrder::$products`  holds an array of **only** `UcOrderProduct` entities (currently it can hold either `UcCartItem` or `UcOrderProduct`, depending on where in the checkout process you check). 

The setting of `$order->products` occurs in one place: inside `uc_cart_checkout()`. So, I'm proposing to make the class conversion right before that point. This is a rather simple process.

This streamlining will allow us to get rid of he rather ugly hack in `uc_order_product_view_multiple()` and it would make the use of specific entity classes more consistent with their original purpose.

PR coming.

**Comment by argiepiano** [comment]
PR #416. 

Explanation:
1. Creates a new helper function that converts `uc_cart_item` entities into `uc_order_product` ones
2. This helper function is invoked right before setting the `$order->products` property in `uc_cart_checkout()`. The order entity will now have only `uc_order_product` entities that use entity class `UcOrderProduct`
3. This makes it possible to remove the hack that converted cart items into order products in `uc_order_product_view_multiple()`, reverting it to the original shape, since we are now certain that the parameter $order_products will always be objects of class `UcOrderProduct`

**Comment by argiepiano** [comment]
We have a test failure. I'll check on this later.

**Comment by argiepiano** [comment]
After more extensive testing I've done additional work on this issue. I've also modified the approach slightly.

1. I've moved the helper function `_uc_cart_items_to_products()` to `_uc_order_cart_items_to_products()`, now in `uc_order.module`. The function now takes an array by reference and makes changes onto the array, without the need to return a value. This function now can also take an array of arrays (instead of an array of objects). This is needed because the `uc_order_edit_form_submit()` function receives an array of products from the form (within `$form_state['values']['products']`). The goal of the helper function is still the same: whenever needed, it takes the keys (or properties) of passed array or object and creates a proper `uc_order_product` entity with those properties. 
2. I've added a method to class `UcOrder`, `UcOrder::setProducts()` which invokes the helper function above and then sets the `$order->products` property.
3. Whenever appropriate, I've replaced instances of `$order->products = XXX` to `$order->setProducts(XXX)` in order to run this method preemptively. 

After all these changes, Ubercart core now will pass `uc_order_products` to `uc_order_product_view_multiple()` regardless of where this invocation happens (whether this happens when the cart if first shown, or when the customer cancels a checkout and goes back to the cart).

In addition, for preemptive reasons (defensive coding) and for backward compatibility with possible custom modules that still may be passing either `stdClass`, `uc_cart_item` or even `node` product objects to  `uc_order_product_view_multiple()`, I have inserted a call to  `_uc_order_cart_items_to_products()` before invoking `entity_plus_view()` in `uc_order_product_view_multiple()`.   This is harmless if the `$order_products` contains `uc_order_product` entities, but it will catch any "old" (D7) way of working with Ubercart entities. 

All of the above is not urgent, but I feel it's a better, more consistent way of doing things, and provides a more robust API.

**Comment by bugfolder** [comment]
> I'm proposing to streamline the code so that `UcOrder::$products` holds an array of only `UcOrderProduct` entities (currently it can hold either `UcCartItem` or `UcOrderProduct`, depending on where in the checkout process you check).

Getting that consistent will be a big help for people developing add-ons or modifications. I will try this out.

**Comment by bugfolder** [comment]
I've tried this out on a (local version of a) real site with several UC and custom modules; everything worked from cart through checkout, packaging, and shipping. No problems or watchdog warnings.

Code reviewed, seems clear and correct to me. Wouldn't mind if @laryn could also put some eyes on it, but from my perspective, looks RTBC.
