### ISSUE TITLE
uc_order_product_load_multiple() doesn't load all uc_order_product entities

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/ubercart#418]
The docblock for `uc_order_product_load_multiple()` says that the first arg is optional, and that if not provided (the default), it loads all uc_order_product entities in the db. This is not the case.

How to reproduce
----

Run `dpm(uc_order_product_load_multiple())` in the devel execute PHP form. It comes back as an empty array. 

~~BTW: the same problem affects `uc_order_load_multiple()`.~~ (Actually no, `uc_order_load_multiple()` requires the first argument.)

The issue is how `entity_load()` is used, which differs in Backdrop from D7.

**Comment by argiepiano** [comment]
PR #419

**Comment by bugfolder** [comment]
Tested:

* `dpm(uc_order_product_load_multiple(FALSE));` returns all.
* `dpm(uc_order_product_load_multiple());` returns all.
* `dpm(uc_order_product_load_multiple(array()));` returns an empty array.

I agree that passing an empty array is a valid use case and the appropriate behavior is to return an empty array.

WFM, LGTM.

Maybe wait a few days just in case any new thoughts pop up, but if none do, I think this is OK to merge.
