### ISSUE TITLE
$conf['i18n_variables'] is cruft

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/ubercart#420]
There are several usages of the (mostly) deprecated global variable `$conf` in Ubercart. They all are of the form `$conf['i18n_variables']`. This was brought over from D7 Ubercart.

`$conf` is a set of the deprecated variables used by `variable_*` functions, which were replaced by config variables in Backdrop and Ubercart.

Moreover, there is no support for anything called `'i18n_variables'` in Backdrop core. In fact, this looks like it might be a residue of something from D6.

In `uc_store.admin.inc`, there's also references to functions `i18n_variable_form_alter_settings` and `i18n_variable_form_selector`, which are also functions that don't exist anywhere in Backdrop core.

So, it would appear that all of this is cruft that can be stripped out of Backdrop Ubercart.

**Comment by bugfolder** [comment]
The variable `i18n_variables` is used in the [D7 Internationalization module](https://www.drupal.org/project/i18n), but isn't in the [Backdrop Internationalization module](https://backdropcms.org/project/i18n), at least, not by that name.

**Comment by argiepiano** [comment]
This does seem to be a leftover from D6. D7 removed `i18n_variables` and moved the content to `i18n_variable_list` and `i18n_variable_conf`. These are part of the submodule `i18n_variable.module` which was used to provide variables that switched values depending on the language context of the page. That module is not included in B's version of i18n, and variables are all gone.

So I agree that those code portions can be safely removed.

**Comment by bugfolder** [comment]
They are removed by the PR.

**Comment by laryn** [comment]
Related: https://github.com/backdrop-contrib/ubercart/issues/287
