### ISSUE TITLE
META: two new labels for the issue queue?

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/ubercart#422]
Just wondering if we should add one or two new labels to for our issue queue:

* "Co-maintainer review" — used when the PR-writer thinks the PR is RTBC but wants another pair of eyes on it before merging.
* "PR ready to be committed" — after the co-maintainer reviews it. (Not sure this one is needed, since the comments have been serving that role, but it might be nice for when scanning the issue queue.)

My practice has been if I write a PR and it's really simple (like the README addition), I'll go ahead and merge it. If it's more complex, I'd like to see another pair of eyes on it before I merge it, and that's what the first label would be for.

There's also an intermediate state, where I'm pretty confident that the PR works so I think it's RTBC, but I hold off on merging just to allow for those situations where I go "oh yeah, that" in the middle of the night. Not sure if we need a label for that.

**Comment by argiepiano** [comment]
I like the idea of adding both labels.

**Comment by bugfolder** [comment]
Cool. Added.
