### ISSUE TITLE
Remove #dependency from views handlers' option_form()

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/ubercart#429]
There are several views handler that still use `#dependency`, which was removed [when Views was incorporated into core](https://github.com/backdrop/backdrop-issues/issues/40). This was used to hide/show elements of the form depending on other elements. This means that, in Backdrop Ubercart, all those elements are shown all the time. 

Instead, core now uses `#states`, and those instances in Ubercart should be replaced.

**Comment by argiepiano** [comment]
PR #434 ready for testing. These two handlers are:
- The Cart ID field when you do a view of Cart Items. De-selecting "Overwrite the value to display for anonymous users" now hides the "Text to display for anonymous users" text input
- The Price/Cost fields in Content/Product views. Selecting "Numeric" now shows all the numeric options such as rounding, etc.

**Comment by herbdool** [comment]
Aha, I just noticed this on geofield as well. This PR looks good to me by the way.

**Comment by argiepiano** [comment]
Thanks. It's also an issue in webform and entity plus.

**Comment by laryn** [comment]
Nice catch! Looks good.

**Comment by bugfolder** [comment]
Also an issue in Me Aliases, it appears.

**Comment by bugfolder** [comment]
Tested this patch:

> The Cart ID field when you do a view of Cart Items. De-selecting "Overwrite the value to display for anonymous users" now hides the "Text to display for anonymous users" text input

Confirmed.

> The Price/Cost fields in Content/Product views. Selecting "Numeric" now shows all the numeric options such as rounding, etc.

Confirmed that it shows numeric options, but the only three options shown are Thousands marker, Prefix, and Suffix; no rounding or anything else. (That was also the case previously, just no appear/disappear behavior.) Should there be more?

![options](https://user-images.githubusercontent.com/29214084/211632349-22f14fb8-aaef-47fc-a444-f017e832a71c.jpg)

**Comment by argiepiano** [comment]
You may be looking at the wrong field or a field that uses a different handler? 

This is what I see when I add a "Sell price" to a view that lists nodes (Products).

<img width="440" alt="Screen Shot 2023-01-10 at 12 08 08 PM" src="https://user-images.githubusercontent.com/9938978/211639978-6108f68d-ba76-46bd-848c-d413eff7502a.png">

When I click Numeric I see Round

<img width="499" alt="Screen Shot 2023-01-10 at 12 08 15 PM" src="https://user-images.githubusercontent.com/9938978/211640036-590ff01c-3215-4713-a131-38ef9f30e0ed.png">

When I click Round I see Precision
<img width="549" alt="Screen Shot 2023-01-10 at 12 08 20 PM" src="https://user-images.githubusercontent.com/9938978/211640132-7f9a3e74-ebae-4d40-978b-06c3b07a251f.png">

**Comment by argiepiano** [comment]
OK, two different fields, two different handlers:

- Display price uses `uc_product_handler_field_display_price` which doesn't include "Round"
- Sell price uses `uc_product_handler_field_price` which does.


The difference has nothing to do with this PR though. I fixed "sell price". Display price was already ok

**Comment by bugfolder** [comment]
Ah, OK. I took "The Price/Cost fields in Content/Product views" to include "Display price", so only checked that one. 

"Sell price" does include rounding. Also "List price." I would think that "Display price" should offer the same options as the other two, but that's a different issue.

Anyhow, all three work with the patch! RTBC.

**Comment by argiepiano** [comment]
This is weird, though, because `uc_product_handler_field_display_price` actually extends `uc_product_handler_field_price`, and it doesn't override the the `options_form()` method, so it should work exactly as the other... unless somehow the names of the form elements have changed in the new form.

I'll check later

**Comment by argiepiano** [comment]
OK, I figured out why the Round option is not appearing in Display price. We need to add  `'float' => TRUE,` to the field definition in `uc_products.view.inc`.

This handler (`uc_product_handler_field_display_price`) could use a bit of TLC. The "refactoring" TODO message is still valid. It's calling its `get_value()` method on every row of the view, instead of using  `pre_render()` to load all the products at once. Not very efficient.

**Comment by bugfolder** [comment]
I created a new issue for the cleanup, so I think this one can be merged at any time.
