### ISSUE TITLE
Customized attribute options not working correctly

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/ubercart#430]
When you customize the price or other properties of an option for a specific product, those customizations are not observed.

To reproduce:

1. Create an attribute in Store > Products > Attributes. For example, "Size"
2. Create some options for that attribute under Operations -> Options. For example "Large", "Medium" and "Small". BE SURE to specify a default sell price adjustment for each option

<img width="1204" alt="Screen Shot 2023-01-08 at 10 44 30 AM" src="https://user-images.githubusercontent.com/9938978/211210970-1ebe2a5e-bc56-4c9a-a3f4-c4fa70c83ae2.png">

3. Now, create a product ("Pants") with a sell price of $40. 
4. After saving the product, edit again and click the Attributes tab. Add "Size" as an attribute
5. Click the "Options" tab to customize the price adjustments for "Pants". Modify the price adjustments (e.g. with crazy numbers)

<img width="1220" alt="Screen Shot 2023-01-08 at 10 48 48 AM" src="https://user-images.githubusercontent.com/9938978/211211147-d6cbb0f6-f8ec-48a1-a430-d4d6c3b514de.png">

6. View the product by clicking View. The price adjustments shown in the select box are still the default (from step 2), not the modified ones from step 5.

<img width="423" alt="Screen Shot 2023-01-08 at 10 50 21 AM" src="https://user-images.githubusercontent.com/9938978/211211212-206c0bc5-ea8c-41e8-ba45-fea608271cb8.png">

**Comment by argiepiano** [comment]
I've checked D7's version of UC and this is working correctly.

**Comment by argiepiano** [comment]
OK, I found the problem: cache! (probably entity cache)

After clearing the cache, the price adjustments are shown correctly. 

I believe the solution is to be sure to programmatically clear the cache when saving customized option adjustments?

**Comment by argiepiano** [comment]
The problem is with [line 1273](https://github.com/backdrop-contrib/ubercart/blob/1.x-3.x/uc_attribute/uc_attribute.admin.inc#L1273) of `uc_attribute.admin.inc`.  Instead of a `cache_clear_all()` we should first check that we are modifying a product (not a product class) and then use `cache_clear_all($form_state['values']['id'], 'cache_entity_node');`

`cache_clear_all()` with no arguments is quite counter-intuitive. It doesn't clear all the caches - only the layout and page caches. Meaning that the node cache is intact.

It looks like this was partly addressed by @laryn last year. He correctly changed a [similar line](https://github.com/backdrop-contrib/ubercart/blob/8c0c47cbc9747ef9f4ffc519e11558fc295bc0e7/uc_attribute/uc_attribute.admin.inc#L910) for the attributes form, but did not change the one for the options form.

**Comment by argiepiano** [comment]
PR #433 submitted and ready for review.

**Comment by bugfolder** [comment]
> `cache_clear_all()` with no arguments is quite counter-intuitive. It doesn't clear all the caches - only the layout and page caches. Meaning that the node cache is intact.

Yeah, I saw a Zulip post not too long ago from someone who got bit by this. They pointed out that [`backdrop_flush_all_caches()`](https://docs.backdropcms.org/api/backdrop/core%21includes%21common.inc/function/backdrop_flush_all_caches/1) is what you want when you really want to clear _all_ caches.

I'll try out the PR.

**Comment by bugfolder** [comment]
First I did this before applying the patch:

* Created options with prices.
* Created a product "Widget" of class Product with those options.
* Edited the product, edited the option.
* Viewed the product. Options had the old price. So bug confirmed.

Did the same thing after applying the patch. Option had the new price. So the patch worked.

Couldn't think of any other scenario that might not be covered, so RTBC.

**Comment by bugfolder** [comment]
BTW, we've got a lot of RTBC issues now (yay, and great going, team!); I'm thinking of going ahead and merging in all RTBCs except the ones that need special mention in the release notes (save those till release time to remember to give the special mention). OK?

**Comment by argiepiano** [comment]
> BTW, we've got a lot of RTBC issues now (yay, and great going, team!); I'm thinking of going ahead and merging in all RTBCs except the ones that need special mention in the release notes (save those till release time to remember to give the special mention). OK?

Sounds good. Just submitted one more PR ready for review - #434
