### ISSUE TITLE
[D7] Fix how UC stock deals with product revisions 

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/ubercart#431]
The issue is described in the [D7 issue queue](https://www.drupal.org/project/ubercart/issues/1637336). Fix has been RTBC there but not merged.  The fix is very simple - DESC sorting the results of a query of node products by revision, so that the latest revision is on top. It's a rare bug, but simple enough to fix.

**Comment by bugfolder** [comment]
Ah, one that I can handle.

Note: give credit to [TR](https://www.drupal.org/u/tr) in the release notes for the D7 patch.

**Comment by argiepiano** [comment]
RTBC!
