### ISSUE TITLE
In uc_roles, _uc_roles_get_choices() always returns all roles

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/ubercart#437]
In `uc_roles` module, the function `_uc_roles_get_choices()` always returns all roles, even if only a subset are checked on the Products configuration page.

This can be seen by observing the "Roles" entry in the status report at `admin/reports/status` (when `uc_roles` is enabled). To test:

* Create several roles.
* In the "Role assignment settings" vertical tab at `admin/store/settings/products`, check one role and save.
* Visit the status report at `admin/reports/status` and observe the "Roles" entry, which will say "The role(s) [all roles listed] are set to be used with the Role Assignment product feature."

This looks like it arose because Backdrop switched to string role keys (from Drupal's numeric keys), so the called to `array_sum()` in the function no longer does what we want. It's a straighforward fix; PR to come.

**Comment by argiepiano** [comment]
Tested and reviewed. LGTM + RTBC!
