### ISSUE TITLE
uc_file: failure to properly validate Downloads and IP addresses in Product settings

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/ubercart#440]
To reproduce:

* Install uc_file (File Downloads module)
* Go to Product settings at `admin/store/settings/products`.
* Click on the "File download settings" vertical tab.
* Make sure "Downloads" and "IP addresses" are empty.
* Click "Save configuration".

Two errors appear:

![errors](https://user-images.githubusercontent.com/29214084/224359189-28671628-9014-4c7d-b878-ec129f58e282.jpg)

They shouldn't appear. Empty should have been accepted.

Now, enter some bogus values: "foobar" or "3.14159". They will be accepted.

These values are set in a couple other places too that suffer the same problems. Search for "Leave empty" to find the validation checks.

**Comment by bugfolder** [comment]
This validation (or similar) appears in three places. To test:

1. Go to `admin/store/settings/products` and click on the "File download settings" vertical tab.
2. Add a file download feature to a product:
  * Create a Product. Click "Save and continue".
  * Click the Features sub-tab.
  * For 'Add a new feature," select "File download" and click Add.
  * Put a file into the Downloads directory. Select the file in the "File download autocomplete".
  * In the File limitations section, check all three override boxes.
  * This will expose Downloads, IP addresses ,and Time fields that are similarly validated (or not, as the case currently is).
3. Add a download file to a user.
  * Go to "Manage User Accounts" at `admin/people/list`.
  * Pick a user and choose "Edit" from the dropbutton.
  * Click the "Files" tab.
  * Open the "Administration" fieldset.
  * Choose a file in "Add file" and click "Save".
  * Re-open the "Administration" fieldset. There are now the three fields visible that are similarly validated (or not, as the case may be).

In all three cases, the three fields should be restricted to positive integers or blank.

**Comment by bugfolder** [comment]
PR submitted.

I changed the error messages to be a bit more friendly ("Your entry does not make sense" is a bit harsh) and, for the Product settings form, to specify exactly which field and in which vertical tab the error is hiding (since the tab with the error ends up un-selected on the error page).

One might suggest changing the `textfield` to `number` (which can, in principle, be automatically validated as positive integers via the `#min` and `#step` properties), but the `number` validation varies across browsers and doesn't allow for the more specific error messages that we're providing.

**Comment by argiepiano** [comment]
@bugfolder, I'm following the steps in the OP and can't reproduce this issue. Therefore I can't test. This may be happening on a D7 upgrade perhaps?

![screencapture](https://user-images.githubusercontent.com/9938978/224459116-fa845620-3cbe-485f-ae3e-8b7dbc9d0a88.gif)

**Comment by argiepiano** [comment]
I also tried your second error scenario, without any problem either. 
![screencapture2](https://user-images.githubusercontent.com/9938978/224459499-d3f2c1ad-8ed8-4a0a-a6b3-d6a0dbe7697c.gif)

**Comment by bugfolder** [comment]
This, too, when I do a fresh install of `uc_file` and `ubercart` modules on Backdrop 1.24.0, I see the error (and it almost has to be there, based on the prior logic). I'm basing everything on the 1.x-3.x branch of Ubercart (latest commit 2/7).

**Comment by argiepiano** [comment]
Thanks, @bugfolder . OK, I was able to reproduce, but only if I use PHP 8.1. The feature works fine in 7.4. Changing the description of the issue to reflect this.

I'll test and review soon.

**Comment by bugfolder** [comment]
The failure to validate still happens in PHP 7.4. Try entering "foo" and "bar" for Downloads and IP Addresses, and you'll see that they're happily accepted. But 7.4 doesn't error on empty values like 8.1 did.

**Comment by argiepiano** [comment]
Sounds good. Changing back the title of the issue to the original one :)

**Comment by argiepiano** [comment]
Tested and reviewed. LGTM. 

One somewhat related issue: In the 3rd scenario above, you can't enter a number bigger than 3 digits in `Downloads` and larger than 2 digits in `Addresses`

**Comment by bugfolder** [comment]
PR updated again; I dropped all of the `#maxlength`s on those positive-integer fields, and also bumped up the `#size` values to allow for larger numbers to stay visible. Once more into the review!

**Comment by argiepiano** [comment]
LGTM. I don't suppose we should worry about the user typing too many characters for the DB field (int)? In my DB (MySQL, MariaDB, or equivalent version 5.7.39) the limit is 11 characters for this int field. Anything bigger gets a fatal error when saving.
