### ISSUE TITLE
Can't set number of file downloads > 999 or number of addresses > 99 for a user

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/ubercart#442]
This was found when testing #440.

Go to "Manage User Accounts" at admin/people/list.
1. Enable File downloads. Set it to work correctly (i.e. set a download folder, put a file there) 
2. Pick a user and choose "Edit" from the dropbutton.
3. Click the "Files" tab.
4. Open the "Administration" fieldset.
5. Choose a file in "Add file" and click "Save".
6. Re-open the "Administration" fieldset. There are now the three fields visible that are similarly validated (or not, as the case may be).
7. Try to enter a number > 999 in Downloads, or > 99 for Addresses. This can't be done

The issue is that `#maxlength` is set to 3 (or 2) for those fields. Other instances of these fields have a `#maxlength` set to 4. Still, why setting `#maxlength` to anything?

**Comment by bugfolder** [comment]
Agreed; no length limitation needed on any of those. (Kinda odd that there's a maximum limitation on a field for setting a maximum limitation.)

Since this is part of validation of those fields, how about I just roll that change into the PR for [#440.](https://github.com/backdrop-contrib/ubercart/issues/440).

**Comment by argiepiano** [comment]
> Since this is part of validation of those fields, how about I just roll that change into the PR for https://github.com/backdrop-contrib/ubercart/issues/440.

Sounds good to me!

**Comment by bugfolder** [comment]
Closing in favor of #440.
