### ISSUE TITLE
Multiple "cURL" entries in the status report

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/ubercart#450]
The status report can list as many as 4 identical entries for "cURL", like this:

![image](https://github.com/backdrop-contrib/ubercart/assets/29214084/9f3d4805-2f91-4111-a4f0-868c18cbac1a)

Three of them are from Ubercart submodules (from `uc_authorizenet_requirements()`, `uc_cybersource_requirements()`, and `uc_paypal_requirements()`; the fourth is from `simpletest_requirements()`, if `simpletest` module is installed.

It's certainly not necessary to list four identical lines, which would make the user wonder if something is amiss to cause the multiple identical rows. Also, none of them have a description field, so there's no clue in the UI where this status notice is even coming from (or that they come from four different modules).

For the Simpletest report, there should probably be a `description` entry that notes that this requirement is coming from Simpletest (and so that would be a separate core issue). For Ubercart, though, there should be a solution that is more informative and that makes sense when more than one payment module is installed (for example, `uc_authorizenet` for credit cards and `uc_paypal` for non-credit-card PayPal).

In fact, I would suggest that if cURL is installed, there's no need for a status notice at all; there's only a need if cURL is missing. So I would suggest that we modify Ubercart's `hook_requirements()` implementations to only post a `REQUIREMENT_ERROR` notice if cURL is missing, and thereby help declutter the status report page.

**Comment by bugfolder** [comment]
In https://github.com/backdrop/backdrop-issues/issues/6121, I've made the argument that Simpletest should be silent on success, i.e., if cURL is present, there's no need for an entry in the status report.

I think the argument for Ubercart to do this is even stronger. Users could use any of the modules mentioned above, and we don't need multiple announcements of the existence of cURL, but if it's missing, it would be OK to have multiple announcements of error, as long as each entry included enough description to specify which module it's coming from.

**Comment by argiepiano** [comment]
@bugfolder - thanks. I left 3 comments in the PR.

**Comment by argiepiano** [comment]
LGTM

**Comment by argiepiano** [comment]
I see you fixed a couple things that had escaped my eyes. LGTM again!
