### ISSUE TITLE
Problems related to the taxonomy_index table and orphaned products

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/ubercart#451]
There are two problems that are related to the taxonomy_index table:

1. `uc_catalog.settings` contains a config variable, `taxonomy_maintain_index_table`. This was derived from the Drupal variable `taxonomy_maintain_index_table`, which became a config variable of the `taxonomy` module named `maintain_index_table`. Thus, Ubercart should not have this variable as a config variable, and in the two places where it's checked, Ubercart should check the `taxonomy.settings` config variable.

2. One of the places where this is checked is in the listing of orphaned products, i.e., products that don't have a catalog taxonomy term. There are a couple of problems with this:
    1. The "Find orphaned products" list at admin/store/products/orphans erroneously lists unpublished products that do have catalog terms as orphans (because the `taxonomy_index` table doesn't contain taxonomy data for unpublished nodes);
    2. The Status Report at admin/reports/status does not show the correct number of orphan products; it should display a warning if there is an orphan product.

To verify these problems, create a vanilla Ubercart installation with a catalog taxonomy, and then create two products: one with a taxonomy term, but unpublished, and a second with no taxonomy terms.

Then visit admin/store/products/orphans. It will include the unpublished (but not-orphan) product.

Visit admin/reports/status. There will not be a warning about the orphan product, but there should be.

PR to follow.

**Comment by argiepiano** [comment]
Good catch! The PR LGTM - I added one small comment.

**Comment by bugfolder** [comment]
PR is updated, thanks for catching that.

**Comment by argiepiano** [comment]
Actually that's not what I meant. the `machine_name` is needed. I'll comment in the PR

**Comment by argiepiano** [comment]
Scratch that! The fix is fine!!! Not sure what I was reading.
