### ISSUE TITLE
Are all dependencies enumerated?

### ISSUE THREAD

**Issue by ericfoy** [backdrop-contrib/ubercart#455]
When installing the Ubercart module, I ran into a glitch: "Unresolved dependencies... Entity_Tokens." Something like that. So I installed Entity_tokens, then Ubercart appeared to install correctly. More testing will disclose whether everything is copacetic.

Meanwhile, I just wanna raise the question: are all dependencies correctly spelled out? Shouldn't Backdrop automatically install and/or prompt me to install dependent modules while installing a module which depends on said modules?

**Comment by bugfolder** [comment]
Ubercart requires Rules module:

```
dependencies[] = rules (>= 2.2.0)
```

And Rules requires Entity Token:

```
dependencies[] = entity_token (>= 2.0.0)
```

So they are at least enumerated correctly.

**Comment by bugfolder** [comment]
No further activity. Looks like this issue is resolved, so closing.
