### ISSUE TITLE
Some Checkout settings not being saved - eg Show the order total preview on the payment pane

### ISSUE THREAD

**Issue by nattywebdev** [backdrop-contrib/ubercart#458]
In Checkout Settings (admin/store/settings/checkout) when I un-check the option for  the Payment Method pane:
Show the order total preview on the payment pane

and save, the setting is not saved.

Likewise, under the Discount codes pane settings, I check:
Show messages about discounts in discounts checkout pane

and save, this setting also is not saved.

Other options are saved just fine (eg: Enable anonymous checkout.). 

Is this a bug or am I doing something unusual?

**Comment by argiepiano** [comment]
I can confirm the problem with the order total setting (which is provided by the submodule `uc_payment`, part of the Ubercart suite). 

@nattywebdev the issue with discount settings not being saved is produced by uc_discount, a separate module. You should create an issue in that issue queue.

**Comment by argiepiano** [comment]
PR ready for testing

**Comment by nattywebdev** [comment]
@argiepiano thank you. Issue with discount settings not being saved now has an issue in that issue queue.
https://github.com/backdrop-contrib/uc_discounts/issues/16
