### ISSUE TITLE
Add vertical tab summary text to Store settings

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/ubercart#462]
See https://github.com/backdrop-contrib/ubercart/issues/424. Add vertical tab settings to admin/store/settings/store.

**Comment by bugfolder** [comment]
I intentionally didn't provide a summary for the first tab because its fields are initially visible on this settings page and it would make for a very tall tab summary to list everything. Thoughts?

**Comment by argiepiano** [comment]
This works great, @bugfolder. I'm ok without providing info for the first tab. RTBC!
