### ISSUE TITLE
Add vertical tab summary text to Checkout settings

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/ubercart#465]
See https://github.com/backdrop-contrib/ubercart/issues/424. Add vertical tab settings to admin/store/settings/checkout.

**Comment by bugfolder** [comment]
Some summaries are already present. We shouldn't list the full Completion messages in the summary. Perhaps only list whether they are filled out or blank?

**Comment by bugfolder** [comment]
Note that these vertical tab summaries are (like Cart settings) in uc_cart.admin.js.

**Comment by argiepiano** [comment]
> Some summaries are already present. We shouldn't list the full Completion messages in the summary. Perhaps only list whether they are filled out or blank?

I think it's OK not to list anything for those in the vertical tabs, unless you think something like "blank" or "custom" may hep? There are many of those... so I'm not sure.

**Comment by bugfolder** [comment]
PR added. Some picking and choosing about what information to show and not.

**Comment by bugfolder** [comment]
@argiepiano, would you take a look at this? (And what do you think about a new bugfix release, given the recent closed issues?)

**Comment by argiepiano** [comment]
I love this! LGTM. New release: yes!
