### ISSUE TITLE
Deprecated function: Using ${var} in strings is deprecated, use {$var} in PHP 8.2

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/ubercart#470]
I'm getting this deprecation notice because of a "dollar sign outside curly braces" [pattern](https://php.watch/versions/8.2/$%7Bvar%7D-string-interpolation-deprecated#:~:text=Deprecated%3A%20Using%20%24%7Bvar%7D%20in,not%20cause%20the%20deprecation%20notice.) This is happening in `uc_store_rfc2822_display_name()`. 

I believe the solution is to just use normal concatenation. The suggested fix in the PHP 8.2 page above may also work, but I'm a bit uneasy about this in this context (this is happening in a `preg_match`). At the very least, this pattern makes the regex even harder to understand.

**Comment by argiepiano** [comment]
It turns out that the suggested change [here](https://github.com/backdrop-contrib/ubercart/issues/470#:~:text=outside%20curly%20braces%22-,pattern,-This%20is%20happening) works just fine both in PHP 8.1 and PHP 8.2. PR ready for review.

To test, use PHP 8.2 and clear caches. Also, to test functionality, enable Rules UI, visit `admin/store/settings/store` and enter a store name that contains quotation marks. Then visit `admin/config/workflow/rules/reaction/manage/uc_checkout_customer_notification/edit/3` and check that the `"` have been escaped as `\"`.

**Comment by bugfolder** [comment]
I went to test this, starting with trying to reproduce the problem. Turned on PHP 8.2.0, entered a store name `My Backdrop ""Site`, then on the Rules action edit page I see the Sender name value `"My Backdrop \"\"Site" <...>`, which is already escaped. But I'm not seeing any deprecation notices. Making the change in this PR doesn't seem to affect anything. Am I missing something?

**Comment by argiepiano** [comment]
Hi @bugfolder. Before the change, with PHP 8.2 you get this when you clear caches:
 
<img width="1156" alt="Screen Shot 2023-11-26 at 4 14 30 PM" src="https://github.com/backdrop-contrib/ubercart/assets/9938978/6daad93c-34ad-478a-8eda-1bc57cdcc884">

After the change there is no deprecation notice. Are you not seeing this in PHP 8.2?

**Comment by argiepiano** [comment]
So, the code was working fine before and after. The problem was not the result. The problem I fixed was the deprecation notice in PHP 8.2. The "testing steps" above were just to show that the functionality still worked as expected after the change.

**Comment by bugfolder** [comment]
I wasn't seeing the deprecation notice, even though I had PHP 8.2. But then I noticed that my contrib module test rig was only on 1.26.0, and so I installed 1.26.1, and poof, deprecation notice appears.

**Comment by bugfolder** [comment]
Seems I spoke too soon. I definitely saw the deprecation notice you quoted when I went to run the update.php from 1.26.0 to 1.26.1, but now, when I clear caches, I don't see any deprecation notice:

![image](https://github.com/backdrop-contrib/ubercart/assets/29214084/6f2a4d11-2f85-4348-bf37-e5d743f57482)

And I do still have my Store set to `My Backdrop ""Site`.

**Comment by bugfolder** [comment]
Ah, but going to `update.php` brings up the notice, even though there aren't any updates to run:

![image](https://github.com/backdrop-contrib/ubercart/assets/29214084/9d61095a-49da-468e-827d-18eebb5b1b6d)

**Comment by bugfolder** [comment]
I can confirm that the notice is repeatable on the update.php screen, and the PR removes the notice from the update.php screen. So, WFM.

**Comment by argiepiano** [comment]
Thanks! Merging...
