### ISSUE TITLE
Credit Card Settings: non-existent directory - Error Message

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/ubercart#479]
I have a fresh installation of Backdrop CMS. I've enabled a few of the ubercart modules and all required modules.

* Ubercart
* Payment
* PayPal
* Payment Method Pack
* Credit Card

When I try to do anything here: http://sitename/admin/store/settings/payment/method/credit

I get an error message that says: "You have specified a non-existent directory."

It does not create any error messages in log. 

![image](https://github.com/backdrop-contrib/ubercart/assets/3144571/bc43e070-426d-44ce-af87-77507e99fbd6)

**Comment by argiepiano** [comment]
Create a directory outside your root. Then click on Security settings and enter the absolute path to that directory.

**Comment by argiepiano** [comment]
You can also create a directory in your private folder and specify `private://MY_DIR`.

**Comment by bugfolder** [comment]
We can (and should) improve the clarity of that error message; since it refers to a vertical tab other than the top one so the highlighted non-validating field isn't visible.

There's a broader issue (and I think I remember seeing a B issue somewhere) about somehow highlighting vertical tab panes when they contain a field that failed validation.

**Comment by bugfolder** [comment]
I've pushed a PR that gives a more informative error message when the directory is non-existent:

![image](https://github.com/backdrop-contrib/ubercart/assets/29214084/1ce68cc9-903d-4b1e-b518-4a2eec20c124)

There are also error messages for other error conditions, and I added some more words to those to help with clarity.

**Comment by argiepiano** [comment]
lgtm!

**Comment by laryn** [comment]
Looks good.

**Comment by nattywebdev** [comment]
Excellent - I came across this just 48 hrs ago and eventually figured out what I'd missed. This addition will really help save people time (and make the issue clearer).

**Comment by stpaultim** [comment]
Thanks everyone. This will be quite helpful. 

I'd like to think that with a little more time I would have figured it out as well. But, who knows....

**Comment by klonos** [comment]
> There's a broader issue (and I think I remember seeing a B issue somewhere) about somehow highlighting vertical tab panes when they contain a field that failed validation.

We have a couple of such issues in core to address the UX problems mentioned in this thread:
- https://github.com/backdrop/backdrop-issues/issues/5504 (focus the vertical tab with the problematic field)
- https://github.com/backdrop/backdrop-issues/issues/5503 (indicate vtabs that contain required fields within them)

I'll rebase the PRs for both of these issues, and we can hopefully have a solution in core soon 😉

**Comment by bugfolder** [comment]
> I'll rebase the PRs for both of these issues, and we can hopefully have a solution in core soon

@ me when they're ready for review, and I'll take a look and try to help them on their way.
