### ISSUE TITLE
Max quantity

### ISSUE THREAD

**Issue by richarda78** [backdrop-contrib/ubercart#483]
Could a max quantity field be added to "Ubercart product settings". A message saying "Max quantity X for this product" should work. I want to set it to 1 as selling unique products.

**Comment by bugfolder** [comment]
Are you wanting to limit to one product per **order**, or one product per **customer** (i.e., do you want to allow them to order two by placing two sequential orders?)

The contrib module https://backdropcms.org/project/uc_product_context supports limiting to one per customer (sequential orders not allowed). Might that address your situation?

**Comment by laryn** [comment]
Or would `uc_stock` work, with each of these set to only have one in stock?

**Comment by bugfolder** [comment]
That, possibly in combination with https://backdropcms.org/project/uc_clearance. With uc_stock, people can buy products that are not in stock (the assumption being that the store will re-order), while uc_clearance doesn't allow buying the item once it's out of stock.

**Comment by bugfolder** [comment]
I've been looking at this vis-a-vis [uc_clearance](https://backdropcms.org/project/uc_clearance) module. I'm a little reluctant to add a new product field to all Ubercart products in all installations; this seems more like a job for a contrib module. 

uc_clearance comes close, but not close enough in its current incarnation. I think, though, that as part of improving uc_clearance (see https://github.com/backdrop-contrib/uc_clearance/issues/2) this desired functionality could be realized with that module.

So, for the moment, I'm going to focus on improving uc_clearance with supporting this use case in mind. When I've got a new version of that module ready, I'll ping back in this issue for you to check out.

**Comment by richarda78** [comment]
That's great @bugfolder - the process could be interrupted at the cart stage with an error message. In the mean time I'll just leave it and assume their customers won't order two or more. Looking forward to the updated module.

**Comment by bugfolder** [comment]
@richarda78, I've made some extensive changes to uc_clearance module that should allow it to accommodate your use case. Would you head on over to [the issue in its issue queue](https://github.com/backdrop-contrib/uc_clearance/issues/2), where we can continue the discussion.

**Comment by bugfolder** [comment]
Looks like uc_clearance meets this need, so closing this issue.
