### ISSUE TITLE
Handle empty suppliers in stock reports

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/ubercart#487]
In PHP 8.1, if the Supplier for a product that is tracked by uc_stock is left empty, then generating the stock report at admin/store/reports/stock/tracked will throw an error for each supplier-less product like this:

> Deprecated function: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in uc_reports_store_csv() (line 1524 of /mysite/modules/contrib/ubercart/uc_reports/uc_reports.admin.inc).

The offending code at line 1524 is:

```
      $row[$index] = '"' . str_replace('"', '""', $column) . '"';
```

If Supplier is left empty, then `$column` is null.

The solution is to replace that line with this:

```
      $row[$index] = is_null($column) ? '""' : '"' . str_replace('"', '""', $column) . '"';
```

which eliminates the error.

**Comment by argiepiano** [comment]
LGTM!
