### ISSUE TITLE
Purchased roles (via uc_roles) lose their expiration so never expire.

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/ubercart#492]
Discovered this on a live site. With a product that has a Role as a feature (user can purchase a time-limited role), the role never expires. Some investigation reveals that the entry in the `uc_rolex_expirations` table vanishes at some time. Further investigation reveals that it vanishes right about the time that a reminder was supposed to be sent out, which traces the problem to the reminder-checking routine, `uc_roles_cron()`. And that, in turn, leads to the culprit, thes lines:

```
    if (!$account || !in_array($expiration->role, array_keys($account->roles))) {
      uc_roles_delete($expiration, $expiration->role, TRUE);
    }
```

That's a holdover from the Drupal days, when `$account->roles` was keyed on the machine name of the role. In Backdrop, it's an ordinary (zero-based-integer-keyed) list whose values are the machine names. So it should be:

```
    if (!$account || !in_array($expiration->role, $account->roles)) {
      uc_roles_delete($expiration, $expiration->role, TRUE);
    }
```

Although this change has been account for in most places, a search through `uc_roles` module turns up one other place where this mistake is being made (fortunately, only in a view page, not a data-altering place like this one). Both are fixed in the PR.

**Comment by laryn** [comment]
Looks good and makes sense.
