### ISSUE TITLE
Replace Store CSS icon in admin bar with Phosphor icon in Backdrop 1.28.0+

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/ubercart#499]
With the addition of admin bar icons in Backdrop 1.28.0, there is now a double-icon on the Store menu in the admin bar: the original CSS icon of a cart, and the generic core icon.

![image](https://github.com/backdrop-contrib/ubercart/assets/29214084/710d8be3-44d4-46cb-874b-2b54b29f47df)

We can replace the CSS icon with the `shopping-cart-fill` or `shopping-card-simple-fill` icon from core icons.

Since there are bugfixes to come in the next release, making the next UC release dependent on Backdrop 1.28.0 seems overly restrictive. Can we check the B version and on that basis decide whether to use the core icon or CSS icon?

**Comment by bugfolder** [comment]
PR added. For Backdrop < 1.28.0, the menu bar looks like this:

![image](https://github.com/backdrop-contrib/ubercart/assets/29214084/1676970e-bf61-470b-b656-1ee02e7cf4bc)

And for 1.28.0 and higher, it looks like this:

![image](https://github.com/backdrop-contrib/ubercart/assets/29214084/c8d6022c-6f73-4f9c-924e-022623af706c)

**Comment by bugfolder** [comment]
BTW, automated tests failed for an unrelated reason, so I've fixed the failing test in the PR.

**Comment by laryn** [comment]
LGTM!

**Comment by bugfolder** [comment]
Thanks, I'll take your "LGTM" is an indication of RTBC and have updated the label. (Any chance you or @argiepiano could check the other "maintainer review requested" issues?)
