### ISSUE TITLE
Operations buttons get duplicated on Manage product classes

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/ubercart#511]
Each subsequent product class gets a multiple of the operation actions. Like this third item.

![Screenshot from 2024-11-06 09-38-11](https://github.com/user-attachments/assets/0ca2e83c-49c5-4f9b-99d9-bfec033d3c18)

**Comment by herbdool** [comment]
@bugfolder a quick PR here.

**Comment by bugfolder** [comment]
I'm not in a position to test right now, but the PR is clear and LGTM.

**Comment by argiepiano** [comment]
LGTM

**Comment by bugfolder** [comment]
When I get back (currently in Germany), I'll merge this, review and (probably) merge the other PRs, and then do a new bugfix release.
