### ISSUE TITLE
Ubercart fields not available as individual field blocks in a layout

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/ubercart#520]
I thought I'd make a more complex layout for product display but the Ubercart fields like SKU, Add to Cart, Display Price, etc are not available.

**Comment by argiepiano** [comment]
Isn't this true for all entity properties? Properties like title, etc, and in the case of Ubercart, SKU, etc, are never available as blocks in core. Only field API fields.

**Comment by argiepiano** [comment]
BTW, you can use [Token Block](https://github.com/backdrop-contrib/token_block) to display product properties in blocks. For example `[node:product:model]` will print the SKU for a node product.

**Comment by herbdool** [comment]
I hadn't thought of that. Thanks for tip. I guess we can close this. (Maybe we need a core issue for exposing properties more easily, but that probably has its own problems.)

**Comment by herbdool** [comment]
The one thing that can't be done with Token Block is the "Add to Cart" form. So I ended up just creating a Views block with a contextual filter for the product and put the fields in there.

**Comment by argiepiano** [comment]
Yes. That's because the Add to Cart form doesn't have a token.
