### ISSUE TITLE
Stock displayed for an attribute option isn't updated correctly on the product page

### ISSUE THREAD

**Issue by nattywebdev** [backdrop-contrib/ubercart#521]
I'm working on a new site with a large number of products (around 3000) - currently it's a live D7 Commerce site that I am rebuilding with Backdrop and Ubercart.

A key issue for my client is stock, which us a product variation level in D7. I'm rebuilding the product collection with attributes and options to replace variations and stock per option is needed. 

[Initially I thought that UC stock doesn't work correctly for attribute options, but I now find that seems to be related to a misconfigured product. Creating a fresh product and adding an attribute with options and stock works perfectly well. ]

However, in conducting this test, I realised that the stock displayed on the add to cart form isn't displayed correctly when you switch from one option to another. 

I assume this is a bug so am reporting it here - unless I'm doing something wrong (if so I'd appreciate guidance!).

Images below show the relevant detail.

Test product default (on page load) - shows 'in stock' before any option selected:
![image](https://github.com/user-attachments/assets/bdc2f51d-90c5-4f54-8b5b-166df1775a29)

Test product with 'Fat Quarter' selected - stock should be 9 (9 is correctly displayed):
![image](https://github.com/user-attachments/assets/26c8b677-0e87-497b-a304-e5194eae0c13)

Test product with 'Fat Eighth' selected  - stock should be 5 (9 is incorrectly displayed):
![image](https://github.com/user-attachments/assets/5372999a-ec05-4525-b0f0-5fcab9d656c8)

Stock displayed from editing node:
![image](https://github.com/user-attachments/assets/3b5fe712-1658-487b-9bd1-852c57d2b734)

**Comment by argiepiano** [comment]
How are you getting Ubercart to display the stock number in the first place? I can't figure that out - I've never used stock.

Is there a chance that this is not updating since the page is showing the cached version?

**Comment by bugfolder** [comment]
I've used `uc_stock`, but I'm not aware of any widget in that module that displays the number in stock. (`uc_clearance` does this, but lists all options in a single comment.) What UC-related modules (contrib and custom) do you have installed?

**Comment by nattywebdev** [comment]
On reflection I think it might be coming from https://github.com/backdrop-contrib/uc_out_of_stock - that makes more sense and I need to transfer the issue there.
Thanks for the guidance @argiepiano and @bugfolder

**Comment by argiepiano** [comment]
Good! Yes, please add an issue there. Closing this one.

**Comment by nattywebdev** [comment]
Transferred to https://github.com/backdrop-contrib/uc_out_of_stock/issues/1
