### ISSUE TITLE
Double check that mail notifications in RULES are set to "Full HTML"

### ISSUE THREAD

**Issue by ProfessorGram** [backdrop-contrib/ubercart#527]
See:

https://backdrop.zulipchat.com/#narrow/channel/218635-Backdrop/topic/.E2.9C.94.20Ubercart.20order.20update.20notification

**Comment by argiepiano** [comment]
The order update rule uses the site's default format. For security and other reasons, I don't think it's a good idea to change this. Closing as not planned.

**Comment by argiepiano** [comment]
Site builders can easily change this by editing the rule btw
