### ISSUE TITLE
Still some entity related bugs

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-contrib/ubercart#73]
Still having some bugs related to the port of the entity stuff, like #69, and other things.

**Comment by robertgarrigos** [comment]
I think #69 is not related to entity porting, however, it seems that cart items are now being registered into the database due to a fix to the entity class. Still, testing to see if I can close this.

**Comment by robertgarrigos** [comment]
right, even cart items don't show, if you click on checkout you get this error:

````
TypeError: Argument 1 passed to filter_entity_insert() must implement interface EntityInterface, instance of UcOrder given, called in /app/core/includes/module.inc on line 945 in filter_entity_insert() (line 1606 of /app/core/modules/filter/filter.module)
````
so, still things to check...

**Comment by docwilmot** [comment]
I'm wondering if we should let Ubercart extend the EMW classes instead of core entity, like we do with Rules. Part of the reason being Ubercart already calls functions that are only provided by EMW so will need to have a dependency.

**Comment by robertgarrigos** [comment]
I'm still having two entity related errors when showing a cart:

```Theme hook "entity" not found.```

and 

```TypeError: Argument 1 passed to filter_entity_insert() must implement interface EntityInterface, instance of UcOrder given, called in /app/core/includes/module.inc on line 945 in filter_entity_insert() (line 1606 of /app/core/modules/filter/filter.module).```
