### ISSUE TITLE
Store address lines set to "NULL", should be empty

### ISSUE THREAD

**Issue by docwilmot** [backdrop-contrib/ubercart#83]
![uc-store-address](https://user-images.githubusercontent.com/1042283/29270187-75d6f2aa-80ed-11e7-8e3e-22f09cffe948.PNG)

**Comment by docwilmot** [comment]
This causes an error with the imported "E-mail admin checkout notification" Rule. The error message is "Error: Missing configuration for parameter addresses".

**Comment by docwilmot** [comment]
Same cause as https://github.com/robertgarrigos/ubercart/issues/72: config defaults have string `"NULL"` as value instead of just being an empty string.

**Comment by robertgarrigos** [comment]
this is fixed but not the error message in the "E-mail admin checkout notification" Rule. (https://github.com/robertgarrigos/ubercart/issues/85)
