### ISSUE TITLE
Checkout panes have no weight or enabled values set

### ISSUE THREAD

**Issue by docwilmot** [backdrop-contrib/ubercart#84]
If you `dpm(_uc_checkout_pane_list())`, the returned panes all have NULL weights and NULL values for 'enabled'. This is needed to set default checkout pane values on install. 

Under `Store>Configuration>Checkout` the basic settings vertical fieldset has a pane which lists available checkout panes; these are all on by default in Drupal Ubercart. This is set in the form builder by lines like `'#default_value' => variable_get('uc_pane_' . $id . '_enabled', $pane['enabled'])`. 

To get this done in Backdrop, we'd need to do in the install file (not complete):
```
  $panes = _uc_checkout_pane_list();
  foreach ($panes as $id => $pane) {
    config_set('uc_cart.settings', 'uc_pane_' . $id . '_enabled', $pane['enabled'])
```

But first, we need to fix pane weights and enabled values.

**Comment by docwilmot** [comment]
Fix added to configs branch https://github.com/robertgarrigos/ubercart/pull/82/commits/aa2eac10c1ad8fd5534ea5e846b3337f95ce3953

**Comment by robertgarrigos** [comment]
Great! Thanks!
