### ISSUE TITLE
Missing configuration for parameter addresses in E-mail admin checkout notification rule

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-contrib/ubercart#85]
after clean install (including rules ui, which needs to be added manually, as there is no dependency with ubercart) and going to admin/config/workflow/rules, E-mail admin checkout notification rule shows an error:

```Error: Missing configuration for parameter addresses.```

**Comment by docwilmot** [comment]
Yes, sorry, wrong answer from me. Its the missing email address which causes this.

**Comment by robertgarrigos** [comment]
got it fixed in local. I will push a branch right now
